---
id: "Spah.SpahQL.QueryRunner"
parent_id: "Spah.SpahQL"
type: class
line_number: 9
description: |
  Class responsible for executing parsed <code>Spah.SpahQL.Query</code> queries and returning sets
  of <code>Spah.SpahQL.QueryResult</code> instances.
  
  Unless you're spelunking or fixing bugs, the only methods you care about are _select_ and _assert_.

file: /Users/danski/Sites/spah/client/src/Spah.SpahQL.QueryRunner.js

---
id: "Spah.SpahQL.QueryRunner.select"
parent_id: "Spah.SpahQL.QueryRunner"
type: class method
line_number: 28
description: |
  Executes a selection query against the given dataset. Returns an array of result instances.

signatures:
 -
  signature: "Spah.SpahQL.QueryRunner.select(query, rootData[,scopeData])"
  return_value: "Array of Spah.SpahQL.QueryResult instances"
arguments:
 -
  name: query
  types: [Spah.SpahQL.Query]
  description: >
    A parsed query instance

 -
  name: rootData
  types: [Object]
  description: >
    The root data context against which to run the query

 -
  name: scopeData
  types: [Object]
  description: >
    An optional additional data context which will be the local scope for this query. If not set, will be set internally to <code>rootData</code>.

file: /Users/danski/Sites/spah/client/src/Spah.SpahQL.QueryRunner.js

---
id: "Spah.SpahQL.QueryRunner.assert"
parent_id: "Spah.SpahQL.QueryRunner"
type: class method
line_number: 45
description: |
  Executes and ssserts the truthiness of a selection or assertion query against the given dataset.
  Returns a boolean indicating the overall result of the query - if the query is not an assertion
  query, it will return true if the query returns one or more results.

signatures:
 -
  signature: "Spah.SpahQL.QueryRunner.assert(query, rootData[, scopeData])"
  return_value: "Boolean result"
arguments:
 -
  name: query
  types: [Spah.SpahQL.Query]
  description: >
    A parsed query instance

 -
  name: rootData
  types: [Object]
  description: >
    The root data context against which to run the query

 -
  name: scopeData
  types: [Object]
  description: >
    An optional additional data context which will be the local scope for this query. If not set, will be set internally to <code>rootData</code>.

file: /Users/danski/Sites/spah/client/src/Spah.SpahQL.QueryRunner.js

---
id: "Spah.SpahQL.QueryRunner.evalQueryToken"
parent_id: "Spah.SpahQL.QueryRunner"
type: class method
line_number: 57
description: |
  Translates a selection query or set literal to a series of results

signatures:
 -
  signature: "Spah.SpahQL.QueryRunner.evalQueryToken(token, data)"
  return_value: "Array of Spah.SpahQL.QueryResult instances"
arguments:
 -
  name: token
  types: [Object]
  description: >
    One of the primary or secondary tokens from a Query instance. May be a selection query or a set literal.

 -
  name: data
  types: [Object]
  description: >
    The data scope against which any selection queries in the token top level will be run.

file: /Users/danski/Sites/spah/client/src/Spah.SpahQL.QueryRunner.js

---
id: "Spah.SpahQL.QueryRunner.evalSelectionQueryToken"
parent_id: "Spah.SpahQL.QueryRunner"
type: class method
line_number: 78
description: |
  Evaluates all the path components in the given query in turn, creating an array of QueryResult instances.

signatures:
 -
  signature: "Spah.SpahQL.QueryRunner.evalSelectionQueryToken(query, rootData, scopeData, scopePath)"
  return_value: "Array of Spah.SpahQL.QueryResult instances"
arguments:
 -
  name: query
  types: [Object]
  description: >
    A selection query token taken from a Query instance.

 -
  name: rootData
  types: [Object]
  description: >
    The entire root-level data structure being queried

 -
  name: scopeData
  types: [Object]
  description: >
    The data for the scope at which this query is being executed.

 -
  name: scopePath
  types: [String]
  description: >
    The string path for the root of the scopeData argument.

file: /Users/danski/Sites/spah/client/src/Spah.SpahQL.QueryRunner.js

---
id: "Spah.SpahQL.QueryRunner.evalSelectionQueryPathComponent"
parent_id: "Spah.SpahQL.QueryRunner"
type: class method
line_number: 116
description: |
  Evaluates a Path Component (e.g. the component "/foo" from the query "/bar/foo") and returns a set of query results.
  Used in evalSelelectionQueryToken to map each path component to a set of results, allowing the query process to be
  effectively forked or halted.

signatures:
 -
  signature: "Spah.SpahQL.QueryRunner.evalSelectionQueryPathComponent(pathComponent, rootData, scopeData, path)"
  return_value: "Array of QueryResults"
arguments:
 -
  name: pathComponent
  types: [Object]
  description: >
    A path component object as generated by the query parser

 -
  name: rootData
  types: [Object]
  description: >
    The entire root-level data structure being queried

 -
  name: scopeData
  types: [Object]
  description: >
    The data for the scope at which this query is being executed.

 -
  name: path
  types: [String]
  description: >
    The string path for the root of the scopeData argument.

file: /Users/danski/Sites/spah/client/src/Spah.SpahQL.QueryRunner.js

---
id: "Spah.SpahQL.QueryRunner.fetchResultsFromObjectByKey"
parent_id: "Spah.SpahQL.QueryRunner"
type: class method
line_number: 165
description: |
  Retrieves the value(s) associated with a given key from the given object, if such a key exists.

signatures:
 -
  signature: "Spah.SpahQL.QueryRunner.fetchResultsFromObjectByKey(key, object, path, recursive)"
  return_value: "Array of QueryResults"
arguments:
 -
  name: key
  types: [String]
  description: >
    The key to be retrieved from the object. Numeric keys in string formare acceptable when accessing arrays.

 -
  name: object
  types: [Object]
  description: >
    The data structure from which the key's associated value will be retrieved

 -
  name: path
  types: [String]
  description: >
    The path at which the item used as the 'object' argument is located

 -
  name: recursive
  types: [Boolean]
  description: >
    A flag indicating whether the key should also be pulled from any child objects of the given object. I N C E P T I O N.

file: /Users/danski/Sites/spah/client/src/Spah.SpahQL.QueryRunner.js

---
id: "Spah.SpahQL.QueryRunner.fetchResultsFromObjectByProperty"
parent_id: "Spah.SpahQL.QueryRunner"
type: class method
line_number: 198
description: |
  Retrieves the specified Spah object property from the given object, if the object supports the specified property.

signatures:
 -
  signature: "Spah.SpahQL.QueryRunner.fetchResultsFromObjectByProperty(key, object, path, recursive)"
  return_value: "Array of QueryResults"
arguments:
 -
  name: key
  types: [String]
  description: >
    The key to be retrieved from the object. Numeric keys in string formare acceptable when accessing arrays.

 -
  name: object
  types: [Object]
  description: >
    The data structure from which the key's associated value will be retrieved

 -
  name: path
  types: [String]
  description: >
    The path at which the item used as the 'object' argument is located

 -
  name: recursive
  types: [Boolean]
  description: >
    A flag indicating whether the key should also be pulled from any child objects of the given object. I N C E P T I O N.

file: /Users/danski/Sites/spah/client/src/Spah.SpahQL.QueryRunner.js

---
id: "Spah.SpahQL.QueryRunner.evalSetLiteralToken"
parent_id: "Spah.SpahQL.QueryRunner"
type: class method
line_number: 250
description: |
  Evaluates a set literal, for use when a set is used in a selection query and must be returned as a set of results.
  If the set is a range, it will be flattened into a set of values.

signatures:
 -
  signature: "Spah.SpahQL.QueryRunner.evalSetLiteralToken(queryToken, rootData[, scopeData])"
  return_value: "Array of QueryResults"
arguments:
 -
  name: queryToken
  types: [Object]
  description: >
    The parsed query token, which must be a set literal

 -
  name: rootData
  types: [Object]
  description: >
    A root data context for any selection queries that appear in the literal

 -
  name: scopeData
  types: [Object]
  description: >
    A scoped data context for the scope at which selection queries in the set will be evaluated.

file: /Users/danski/Sites/spah/client/src/Spah.SpahQL.QueryRunner.js

---
id: "Spah.SpahQL.QueryRunner.evalNumericRange"
parent_id: "Spah.SpahQL.QueryRunner"
type: class method
line_number: 291
description: |
  Evaluates a numeric range literal, generating an array of QueryResults containing all values in the range.

signatures:
 -
  signature: "Spah.SpahQL.QueryRunner.evalNumericRange(start, end)"
  return_value: "Array of QueryResults"
arguments:
 -
  name: start
  types: [Number]
  description: >
    The number at the start of the range (10 is the start value for {10..8})

 -
  name: end
  types: [Number]
  description: >
    The number at the start of the range (8 is the end value for {10..8})

file: /Users/danski/Sites/spah/client/src/Spah.SpahQL.QueryRunner.js

---
id: "Spah.SpahQL.QueryRunner.evalStringRange"
parent_id: "Spah.SpahQL.QueryRunner"
type: class method
line_number: 314
description: |
  Evaluates a string range literal, generating an array of QueryResults containing all values in the range.
  String range literals are evaluated as numeric ranges using a radix of 35, and transposing the generated numeric values
  back into strings before returning them.

signatures:
 -
  signature: "Spah.SpahQL.QueryRunner.evalStringRange(start, end)"
  return_value: "Array of QueryResults"
arguments:
 -
  name: start
  types: [String]
  description: >
    The character at the start of the range ("a" is the start value for {'a'..'c'})

 -
  name: end
  types: [String]
  description: >
    The character at the end of the range ("c" is the end value for {'a'..'c'})

file: /Users/danski/Sites/spah/client/src/Spah.SpahQL.QueryRunner.js

---
id: "Spah.SpahQL.QueryRunner.evalAssertion"
parent_id: "Spah.SpahQL.QueryRunner"
type: class method
line_number: 343
description: |
  Executes an assertion query. If the secondary token is null, then the primary token will be evaluated and the assertion
  will be successful (returning true) if the primary resultset contains one or more "truthy" values (i.e. if it is not simply
  full of nulls and/or false values). If the secondary token is provided, then the two tokens will be evaluated and their
  result sets compared using the provided operator.

signatures:
 -
  signature: "Spah.SpahQL.QueryRunner.evalAssertion(primaryToken, secondaryToken, comparisonOperator, rootData, scopeData)"
  return_value: "Boolean result"
arguments:
 -
  name: primaryToken
  types: [Object]
  description: >
    A selection query or set literal token as delivered by the query parser.

 -
  name: secondaryToken
  types: [Object]
  description: >
    A selection query or set literal token as delivered by the query parser. May be null.

 -
  name: comparisonOperator
  types: [String]
  description: >
    The comparison operator that will be used to compare the primary and secondary result sets.

 -
  name: rootData
  types: [Object]
  description: >
    A root data context for any selection queries that appear in the literal

 -
  name: scopeData
  types: [Object]
  description: >
    A scoped data context for the scope at which selection queries in the set will be evaluated.

file: /Users/danski/Sites/spah/client/src/Spah.SpahQL.QueryRunner.js