---
id: "Spah.State.Query"
parent_id: "Spah.State"
type: class
line_number: 7
description: |
  A <code>Query</code> instance is the result of running a string state query such as "/foo/bar/baz == 1" through the <code>Spah.State.QueryParser</code>.
  Queries are parsed only once, upon registration. The QueryParser maintains a cache of pre-existing parsed queries keyed by the original query string.

file: /Users/danski/Sites/spah/client/src/Spah.State.Query.js

---
id: "Spah.State.Query#rawString"
parent_id: "Spah.State.Query"
type: instance property
line_number: 25
description: |
  The string from which this query was originally parsed.

signatures:
 -
  signature: "Spah.State.Query#rawString"
  return_value: "String original representation"
file: /Users/danski/Sites/spah/client/src/Spah.State.Query.js

---
id: "Spah.State.Query#fragments"
parent_id: "Spah.State.Query"
type: instance property
line_number: 35
description: |
  The fragments into which this query was parsed. When the query is executed,
  each fragment is executed in turn on the data returned by the last. If any fragment
  returns false or an empty resultset, the query is terminated and the failure result
  returned.

signatures:
 -
  signature: "Spah.State.Query#fragments"
  return_value: "Array of parsed query fragments"
file: /Users/danski/Sites/spah/client/src/Spah.State.Query.js

---
id: "Spah.State.Query#isTruthy"
parent_id: "Spah.State.Query"
type: instance method
line_number: 43
description: |
  Responds with <code>true</code> if this query is a comparison query that should return <code>true</code> or <code>false</code>
  instead of a resultset.

signatures:
 -
  signature: "Spah.State.Query#isTruthy()"
  return_value: "Boolean isTruthy"
file: /Users/danski/Sites/spah/client/src/Spah.State.Query.js