---
id: "Spah.State.Query"
parent_id: "Spah.State"
type: class
line_number: 7
description: |
  A <code>Query</code> instance is the result of running a string state query such as "/foo/bar/baz == 1" through the <code>Spah.State.QueryParser</code>.
  Queries are parsed only once, upon registration. The QueryParser maintains a cache of pre-existing parsed queries keyed by the original query string.

file: /Users/danski/Sites/spah/client/src/Spah.State.Query.js

---
id: "Spah.State.Query#rawString"
parent_id: "Spah.State.Query"
type: instance property
line_number: 25
description: |
  The string from which this query was originally parsed.

signatures:
 -
  signature: "Spah.State.Query#rawString"
  return_value: "String original representation"
file: /Users/danski/Sites/spah/client/src/Spah.State.Query.js

---
id: "Spah.State.Query#primaryToken"
parent_id: "Spah.State.Query"
type: instance property
line_number: 32
description: |
  The first (non-optional) token in the query.

signatures:
 -
  signature: "Spah.State.Query#primaryToken"
  return_value: "Primary token (set literal or selection query)"
file: /Users/danski/Sites/spah/client/src/Spah.State.Query.js

---
id: "Spah.State.Query#comparisonOperator"
parent_id: "Spah.State.Query"
type: instance property
line_number: 40
description: |
  The optional comparison operator. If this is set, the query is an assertion query and there must
  be a secondary token defined.

signatures:
 -
  signature: "Spah.State.Query#comparisonOperator"
  return_value: "String comparison operator"
file: /Users/danski/Sites/spah/client/src/Spah.State.Query.js

---
id: "Spah.State.Query#primaryToken"
parent_id: "Spah.State.Query"
type: instance property
line_number: 47
description: |
  The second (optional) token in the query. Cannot be defined without a comparison operator.

signatures:
 -
  signature: "Spah.State.Query#primaryToken"
  return_value: "Primary token (set literal or selection query)"
file: /Users/danski/Sites/spah/client/src/Spah.State.Query.js

---
id: "Spah.State.Query#assertion"
parent_id: "Spah.State.Query"
type: instance property
line_number: 54
description: |
  Set to <code>true</code> if the query is an assertion query.

signatures:
 -
  signature: "Spah.State.Query#assertion"
  return_value: "Boolean assertion flag"
file: /Users/danski/Sites/spah/client/src/Spah.State.Query.js