---
id: "Spah.SpahQL.Token.KeyName"
parent_id: "Spah.SpahQL.Token"
type: class
superclass_id: "Spah.SpahQL.Token.Simple"
line_number: 6
description: |
  A simple token wrapping a valid variable or identifier value.

file: /Users/danski/Sites/spah/client/src/Spah.SpahQL.Token.KeyName.js

---
id: "Spah.SpahQL.Token.KeyName.parseAt"
parent_id: "Spah.SpahQL.Token.KeyName"
type: class method
line_number: 20
description: |
  Identifies a keyname identifier at the given index in the given string query and returns null
  if no token is identified, or a tuple of terminating index and the instantiated token if successful.

signatures:
 -
  signature: "Spah.SpahQL.Token.KeyName.parseAt(i, query)"
  return_value: "Array\\[resumeIndex, foundToken\\] or null"
file: /Users/danski/Sites/spah/client/src/Spah.SpahQL.Token.KeyName.js