/**
 * class Spah
 * 
 *
 *
 * For more information on Spah, see the main [Readme on Github](https://github.com/danski/spah#readme).
 **/
Spah = function() {};

jQuery.extend(Spah, {
  
  /**
   * Spah.logMessages -> Array
   * A stored array of all messages generated by Spah's logging system.
   **/
  "logMessages": [],
  /**
   * Spah.verbose -> Boolean
   * Set to <true>true</true> if you wish Spah to produce debug output in the browser's console.
   **/
  "verbose": false,
  
  /**
   * Spah.boot(options) -> Null
   * desc
   * description
   **/
  "boot": function(options) {
    
  },
  
  /**
   * Spah.log(message) -> String message
   * Logs debug output to Spah's internal logger. If Spah.verbose is set to true, the message will appear in the browser's console.
   **/
  "log": function(message) {
    this.logMessages.push(message);
    if(this.verbose && window.console) {
      console.log(message);
    }
    return message;
  }
});

// Compiler exports
window["Spah"] = Spah;