if (!window.PDoc) window.PDoc = {};
PDoc.elements = {
  'Spah.SpahQL.Token.PathComponent.parseAt': { 'name': 'Spah.SpahQL.Token.PathComponent.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/PathComponent/parseAt/index.html' },
'Spah.SpahQL.Query#secondaryToken': { 'name': 'Spah.SpahQL.Query#secondaryToken', 'type': 'instance property', 'path': 'Spah/SpahQL/Query/prototype/secondaryToken/index.html' },
'Spah.SpahQL.QueryParser.queryCache': { 'name': 'Spah.SpahQL.QueryParser.queryCache', 'type': 'class property', 'path': 'Spah/SpahQL/QueryParser/queryCache/index.html' },
'Spah.DOM.Modifiers.ClassName.up': { 'name': 'Spah.DOM.Modifiers.ClassName.up', 'type': 'class method', 'path': 'Spah/DOM/Modifiers/ClassName/up/index.html' },
'Spah.DOM.Modifiers.ClassName.down': { 'name': 'Spah.DOM.Modifiers.ClassName.down', 'type': 'class method', 'path': 'Spah/DOM/Modifiers/ClassName/down/index.html' },
'Spah.SpahQL#parents': { 'name': 'Spah.SpahQL#parents', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/parents/index.html' },
'Spah.SpahQL.Errors': { 'name': 'Spah.SpahQL.Errors', 'type': 'class', 'path': 'Spah/SpahQL/Errors/index.html' },
'Spah.SpahQL.QueryParser.parseQuery': { 'name': 'Spah.SpahQL.QueryParser.parseQuery', 'type': 'class method', 'path': 'Spah/SpahQL/QueryParser/parseQuery/index.html' },
'Spah.SpahQL#last': { 'name': 'Spah.SpahQL#last', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/last/index.html' },
'Spah.SpahQL#parentPath': { 'name': 'Spah.SpahQL#parentPath', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/parentPath/index.html' },
'Spah.DOM.Modifiers.ElementId.up': { 'name': 'Spah.DOM.Modifiers.ElementId.up', 'type': 'class method', 'path': 'Spah/DOM/Modifiers/ElementId/up/index.html' },
'Spah.SpahQL.Token.PathComponent#evaluate': { 'name': 'Spah.SpahQL.Token.PathComponent#evaluate', 'type': 'instance method', 'path': 'Spah/SpahQL/Token/PathComponent/prototype/evaluate/index.html' },
'Spah.SpahQL.DataHelper.gteSet': { 'name': 'Spah.SpahQL.DataHelper.gteSet', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/gteSet/index.html' },
'Spah.SpahQL.Token.KeyName': { 'name': 'Spah.SpahQL.Token.KeyName', 'type': 'class', 'path': 'Spah/SpahQL/Token/KeyName/index.html' },
'Spah.SpahQL.Token.String': { 'name': 'Spah.SpahQL.Token.String', 'type': 'class', 'path': 'Spah/SpahQL/Token/String/index.html' },
'Spah.DOM.Modifiers.Show.actionName': { 'name': 'Spah.DOM.Modifiers.Show.actionName', 'type': 'class method', 'path': 'Spah/DOM/Modifiers/Show/actionName/index.html' },
'Spah.StateServer#addExpander': { 'name': 'Spah.StateServer#addExpander', 'type': 'instance method', 'path': 'Spah/StateServer/prototype/addExpander/index.html' },
'Spah.SpahQL.Callbacks': { 'name': 'Spah.SpahQL.Callbacks', 'type': 'class', 'path': 'Spah/SpahQL/Callbacks/index.html' },
'Spah.SpahQL.Token.PathComponent#fetchResultsFromObjectByKey': { 'name': 'Spah.SpahQL.Token.PathComponent#fetchResultsFromObjectByKey', 'type': 'instance method', 'path': 'Spah/SpahQL/Token/PathComponent/prototype/fetchResultsFromObjectByKey/index.html' },
'Spah.SpahQL.Token.PathComponent#recursive': { 'name': 'Spah.SpahQL.Token.PathComponent#recursive', 'type': 'instance property', 'path': 'Spah/SpahQL/Token/PathComponent/prototype/recursive/index.html' },
'Spah.SpahQL.Query#assertion': { 'name': 'Spah.SpahQL.Query#assertion', 'type': 'instance property', 'path': 'Spah/SpahQL/Query/prototype/assertion/index.html' },
'Spah.SpahQL.DataHelper.eqSetStrict': { 'name': 'Spah.SpahQL.DataHelper.eqSetStrict', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/eqSetStrict/index.html' },
'Spah.StateServer': { 'name': 'Spah.StateServer', 'type': 'class', 'path': 'Spah/StateServer/index.html' },
'Spah.SpahQL#keyName': { 'name': 'Spah.SpahQL#keyName', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/keyName/index.html' },
'Spah.SpahQL#containing': { 'name': 'Spah.SpahQL#containing', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/containing/index.html' },
'Spah.SpahQL.Callbacks.callbacks': { 'name': 'Spah.SpahQL.Callbacks.callbacks', 'type': 'class property', 'path': 'Spah/SpahQL/Callbacks/callbacks/index.html' },
'Spah.DOM.Modifiers.Show': { 'name': 'Spah.DOM.Modifiers.Show', 'type': 'class', 'path': 'Spah/DOM/Modifiers/Show/index.html' },
'new Spah.SpahQL.Token.SelectionQuery': { 'name': 'new Spah.SpahQL.Token.SelectionQuery', 'type': 'constructor', 'path': 'Spah/SpahQL/Token/SelectionQuery/new/index.html' },
'Spah.SpahQL.Token.Base': { 'name': 'Spah.SpahQL.Token.Base', 'type': 'class', 'path': 'Spah/SpahQL/Token/Base/index.html' },
'Spah.DOM.Document.defaultModifiers': { 'name': 'Spah.DOM.Document.defaultModifiers', 'type': 'class property', 'path': 'Spah/DOM/Document/defaultModifiers/index.html' },
'Spah.SpahQL.Token.PathComponent': { 'name': 'Spah.SpahQL.Token.PathComponent', 'type': 'class', 'path': 'Spah/SpahQL/Token/PathComponent/index.html' },
'Spah.SpahQL.QueryParser.cleanQuery': { 'name': 'Spah.SpahQL.QueryParser.cleanQuery', 'type': 'class method', 'path': 'Spah/SpahQL/QueryParser/cleanQuery/index.html' },
'Spah.SpahQL.Token.FilterQuery.parseAt': { 'name': 'Spah.SpahQL.Token.FilterQuery.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/FilterQuery/parseAt/index.html' },
'Spah.SpahQL.DataHelper.deepClone': { 'name': 'Spah.SpahQL.DataHelper.deepClone', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/deepClone/index.html' },
'Spah.SpahQL.Token.String.parseAt': { 'name': 'Spah.SpahQL.Token.String.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/String/parseAt/index.html' },
'Spah.SpahQL#value': { 'name': 'Spah.SpahQL#value', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/value/index.html' },
'Spah.SpahQL.db': { 'name': 'Spah.SpahQL.db', 'type': 'class method', 'path': 'Spah/SpahQL/db/index.html' },
'Spah.SpahQL.Token.Boolean': { 'name': 'Spah.SpahQL.Token.Boolean', 'type': 'class', 'path': 'Spah/SpahQL/Token/Boolean/index.html' },
'Spah.SpahQL#values': { 'name': 'Spah.SpahQL#values', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/values/index.html' },
'Spah.SpahQL.Token.Numeric': { 'name': 'Spah.SpahQL.Token.Numeric', 'type': 'class', 'path': 'Spah/SpahQL/Token/Numeric/index.html' },
'Spah.SpahQL.QueryRunner.evalAssertion': { 'name': 'Spah.SpahQL.QueryRunner.evalAssertion', 'type': 'class method', 'path': 'Spah/SpahQL/QueryRunner/evalAssertion/index.html' },
'Spah.SpahQL.Query#primaryToken': { 'name': 'Spah.SpahQL.Query#primaryToken', 'type': 'instance property', 'path': 'Spah/SpahQL/Query/prototype/primaryToken/index.html' },
'Spah.SpahQL.DataHelper.eqHashRough': { 'name': 'Spah.SpahQL.DataHelper.eqHashRough', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/eqHashRough/index.html' },
'Spah.inBrowser': { 'name': 'Spah.inBrowser', 'type': 'class method', 'path': 'Spah/inBrowser/index.html' },
'Spah.SpahQL.Token.Set#evalStringRange': { 'name': 'Spah.SpahQL.Token.Set#evalStringRange', 'type': 'instance method', 'path': 'Spah/SpahQL/Token/Set/prototype/evalStringRange/index.html' },
'Spah.SpahQL#resultModified': { 'name': 'Spah.SpahQL#resultModified', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/resultModified/index.html' },
'Spah.SpahQL.assert': { 'name': 'Spah.SpahQL.assert', 'type': 'class method', 'path': 'Spah/SpahQL/assert/index.html' },
'Spah.StateServer#identifyWarmRequest': { 'name': 'Spah.StateServer#identifyWarmRequest', 'type': 'instance method', 'path': 'Spah/StateServer/prototype/identifyWarmRequest/index.html' },
'Spah.DOM.Errors.InvalidModifierError': { 'name': 'Spah.DOM.Errors.InvalidModifierError', 'type': 'class', 'path': 'Spah/DOM/Errors/InvalidModifierError/index.html' },
'new Spah.SpahQL.Token.PathComponent': { 'name': 'new Spah.SpahQL.Token.PathComponent', 'type': 'constructor', 'path': 'Spah/SpahQL/Token/PathComponent/new/index.html' },
'Spah.SpahQL.DataHelper.gtSet': { 'name': 'Spah.SpahQL.DataHelper.gtSet', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/gtSet/index.html' },
'Spah.SpahQL.DataHelper.lteSet': { 'name': 'Spah.SpahQL.DataHelper.lteSet', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/lteSet/index.html' },
'Spah.SpahQL.DataHelper.mathLte': { 'name': 'Spah.SpahQL.DataHelper.mathLte', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/mathLte/index.html' },
'new Spah.State': { 'name': 'new Spah.State', 'type': 'constructor', 'path': 'Spah/State/new/index.html' },
'Spah.SpahQL.Token.Set#evalNumericRange': { 'name': 'Spah.SpahQL.Token.Set#evalNumericRange', 'type': 'instance method', 'path': 'Spah/SpahQL/Token/Set/prototype/evalNumericRange/index.html' },
'Spah.SpahQL': { 'name': 'Spah.SpahQL', 'type': 'class', 'path': 'Spah/SpahQL/index.html' },
'Spah.SpahQL#clone': { 'name': 'Spah.SpahQL#clone', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/clone/index.html' },
'Spah.SpahQL.Token.SelectionQuery#pathComponents': { 'name': 'Spah.SpahQL.Token.SelectionQuery#pathComponents', 'type': 'instance property', 'path': 'Spah/SpahQL/Token/SelectionQuery/prototype/pathComponents/index.html' },
'Spah.SpahQL.Token.FilterQuery#evaluate': { 'name': 'Spah.SpahQL.Token.FilterQuery#evaluate', 'type': 'instance method', 'path': 'Spah/SpahQL/Token/FilterQuery/prototype/evaluate/index.html' },
'Spah.SpahQL#paths': { 'name': 'Spah.SpahQL#paths', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/paths/index.html' },
'Spah.SpahQL#parentPaths': { 'name': 'Spah.SpahQL#parentPaths', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/parentPaths/index.html' },
'Spah.SpahQL.DataHelper.objectType': { 'name': 'Spah.SpahQL.DataHelper.objectType', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/objectType/index.html' },
'Spah.SpahQL.Token.ComparisonOperator.parseAt': { 'name': 'Spah.SpahQL.Token.ComparisonOperator.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/ComparisonOperator/parseAt/index.html' },
'Spah.SpahQL.Callbacks.pathModifiedOnObject': { 'name': 'Spah.SpahQL.Callbacks.pathModifiedOnObject', 'type': 'class method', 'path': 'Spah/SpahQL/Callbacks/pathModifiedOnObject/index.html' },
'Spah.SpahQL.Token.Base.parseAt': { 'name': 'Spah.SpahQL.Token.Base.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/Base/parseAt/index.html' },
'Spah.SpahQL.QueryRunner.select': { 'name': 'Spah.SpahQL.QueryRunner.select', 'type': 'class method', 'path': 'Spah/SpahQL/QueryRunner/select/index.html' },
'Spah.SpahQL.DataHelper.compare': { 'name': 'Spah.SpahQL.DataHelper.compare', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/compare/index.html' },
'Spah.DOM.Document#addModifiers': { 'name': 'Spah.DOM.Document#addModifiers', 'type': 'instance method', 'path': 'Spah/DOM/Document/prototype/addModifiers/index.html' },
'Spah.SpahQL.QueryParser': { 'name': 'Spah.SpahQL.QueryParser', 'type': 'class', 'path': 'Spah/SpahQL/QueryParser/index.html' },
'Spah.SpahQL.DataHelper.eqSetRough': { 'name': 'Spah.SpahQL.DataHelper.eqSetRough', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/eqSetRough/index.html' },
'Spah.SpahQL.Errors.SpahQLRunTimeError': { 'name': 'Spah.SpahQL.Errors.SpahQLRunTimeError', 'type': 'class', 'path': 'Spah/SpahQL/Errors/SpahQLRunTimeError/index.html' },
'Spah.DOM.Document#removeModifiers': { 'name': 'Spah.DOM.Document#removeModifiers', 'type': 'instance method', 'path': 'Spah/DOM/Document/prototype/removeModifiers/index.html' },
'Spah.SpahQL.DataHelper.superSet': { 'name': 'Spah.SpahQL.DataHelper.superSet', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/superSet/index.html' },
'Spah.DOM.Modifiers.ClassName': { 'name': 'Spah.DOM.Modifiers.ClassName', 'type': 'class', 'path': 'Spah/DOM/Modifiers/ClassName/index.html' },
'Spah': { 'name': 'Spah', 'type': 'class', 'path': 'Spah/index.html' },
'Spah.DOM.Document#addTemplate': { 'name': 'Spah.DOM.Document#addTemplate', 'type': 'instance method', 'path': 'Spah/DOM/Document/prototype/addTemplate/index.html' },
'Spah.SpahQL#set': { 'name': 'Spah.SpahQL#set', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/set/index.html' },
'Spah.SpahQL#delete': { 'name': 'Spah.SpahQL#delete', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/delete/index.html' },
'Spah.StateClient#reduceState': { 'name': 'Spah.StateClient#reduceState', 'type': 'instance method', 'path': 'Spah/StateClient/prototype/reduceState/index.html' },
'Spah.SpahQL.QueryRunner': { 'name': 'Spah.SpahQL.QueryRunner', 'type': 'class', 'path': 'Spah/SpahQL/QueryRunner/index.html' },
'Spah.SpahQL#replaceAll': { 'name': 'Spah.SpahQL#replaceAll', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/replaceAll/index.html' },
'Spah.SpahQL.DataHelper.eqBooleanRough': { 'name': 'Spah.SpahQL.DataHelper.eqBooleanRough', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/eqBooleanRough/index.html' },
'Spah.SpahQL.DataHelper.mathGt': { 'name': 'Spah.SpahQL.DataHelper.mathGt', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/mathGt/index.html' },
'Spah.SpahQL#map': { 'name': 'Spah.SpahQL#map', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/map/index.html' },
'Spah.SpahQL.Token.SelectionQuery#useRoot': { 'name': 'Spah.SpahQL.Token.SelectionQuery#useRoot', 'type': 'instance property', 'path': 'Spah/SpahQL/Token/SelectionQuery/prototype/useRoot/index.html' },
'Spah.DOM.Modifiers.ClassName.actionName': { 'name': 'Spah.DOM.Modifiers.ClassName.actionName', 'type': 'class method', 'path': 'Spah/DOM/Modifiers/ClassName/actionName/index.html' },
'Spah.SpahQL.Token.Set.parseAt': { 'name': 'Spah.SpahQL.Token.Set.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/Set/parseAt/index.html' },
'Spah.SpahQL.Token.Simple': { 'name': 'Spah.SpahQL.Token.Simple', 'type': 'class', 'path': 'Spah/SpahQL/Token/Simple/index.html' },
'new Spah.SpahQL': { 'name': 'new Spah.SpahQL', 'type': 'constructor', 'path': 'Spah/SpahQL/new/index.html' },
'Spah.verbose': { 'name': 'Spah.verbose', 'type': 'class property', 'path': 'Spah/verbose/index.html' },
'Spah.isHeadless': { 'name': 'Spah.isHeadless', 'type': 'class method', 'path': 'Spah/isHeadless/index.html' },
'Spah.SpahQL.Token.PathComponent#key': { 'name': 'Spah.SpahQL.Token.PathComponent#key', 'type': 'instance property', 'path': 'Spah/SpahQL/Token/PathComponent/prototype/key/index.html' },
'Spah.SpahQL.Token.Set': { 'name': 'Spah.SpahQL.Token.Set', 'type': 'class', 'path': 'Spah/SpahQL/Token/Set/index.html' },
'Spah.SpahQL.Token.SelectionQuery#evaluate': { 'name': 'Spah.SpahQL.Token.SelectionQuery#evaluate', 'type': 'instance method', 'path': 'Spah/SpahQL/Token/SelectionQuery/prototype/evaluate/index.html' },
'Spah.SpahQL.DataHelper.jointSetWithCallback': { 'name': 'Spah.SpahQL.DataHelper.jointSetWithCallback', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/jointSetWithCallback/index.html' },
'new Spah.SpahQL.Token.Simple': { 'name': 'new Spah.SpahQL.Token.Simple', 'type': 'constructor', 'path': 'Spah/SpahQL/Token/Simple/new/index.html' },
'Spah.SpahQL#type': { 'name': 'Spah.SpahQL#type', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/type/index.html' },
'Spah.SpahQL#setAll': { 'name': 'Spah.SpahQL#setAll', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/setAll/index.html' },
'Spah.SpahQL#types': { 'name': 'Spah.SpahQL#types', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/types/index.html' },
'Spah.SpahQL.DataHelper.hashValues': { 'name': 'Spah.SpahQL.DataHelper.hashValues', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/hashValues/index.html' },
'Spah.SpahQL.DataHelper': { 'name': 'Spah.SpahQL.DataHelper', 'type': 'class', 'path': 'Spah/SpahQL/DataHelper/index.html' },
'Spah.DOM.Errors': { 'name': 'Spah.DOM.Errors', 'type': 'class', 'path': 'Spah/DOM/Errors/index.html' },
'Spah.SpahQL.QueryParser.throwParseErrorAt': { 'name': 'Spah.SpahQL.QueryParser.throwParseErrorAt', 'type': 'class method', 'path': 'Spah/SpahQL/QueryParser/throwParseErrorAt/index.html' },
'Spah.State': { 'name': 'Spah.State', 'type': 'class', 'path': 'Spah/State/index.html' },
'Spah.SpahQL.Token#toSet': { 'name': 'Spah.SpahQL.Token#toSet', 'type': 'instance method', 'path': 'Spah/SpahQL/Token/prototype/toSet/index.html' },
'Spah.SpahQL.DataHelper.eqArrayRough': { 'name': 'Spah.SpahQL.DataHelper.eqArrayRough', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/eqArrayRough/index.html' },
'Spah.classExtend': { 'name': 'Spah.classExtend', 'type': 'class method', 'path': 'Spah/classExtend/index.html' },
'Spah.State#clone': { 'name': 'Spah.State#clone', 'type': 'instance method', 'path': 'Spah/State/prototype/clone/index.html' },
'Spah.SpahQL.Token.PathComponent#property': { 'name': 'Spah.SpahQL.Token.PathComponent#property', 'type': 'instance property', 'path': 'Spah/SpahQL/Token/PathComponent/prototype/property/index.html' },
'Spah.init': { 'name': 'Spah.init', 'type': 'class method', 'path': 'Spah/init/index.html' },
'Spah.DOM.Modifiers.ElementId.down': { 'name': 'Spah.DOM.Modifiers.ElementId.down', 'type': 'class method', 'path': 'Spah/DOM/Modifiers/ElementId/down/index.html' },
'Spah.SpahQL.Token.Simple#evaluate': { 'name': 'Spah.SpahQL.Token.Simple#evaluate', 'type': 'instance method', 'path': 'Spah/SpahQL/Token/Simple/prototype/evaluate/index.html' },
'Spah.DOM.Blueprint#toString': { 'name': 'Spah.DOM.Blueprint#toString', 'type': 'instance method', 'path': 'Spah/DOM/Blueprint/prototype/toString/index.html' },
'Spah.DOM.Blueprint.compile': { 'name': 'Spah.DOM.Blueprint.compile', 'type': 'class method', 'path': 'Spah/DOM/Blueprint/compile/index.html' },
'Spah.SpahQL.Token.throwParseErrorAt': { 'name': 'Spah.SpahQL.Token.throwParseErrorAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/throwParseErrorAt/index.html' },
'Spah.classCreate': { 'name': 'Spah.classCreate', 'type': 'class method', 'path': 'Spah/classCreate/index.html' },
'Spah.SpahQL#each': { 'name': 'Spah.SpahQL#each', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/each/index.html' },
'Spah.SpahQL.DataHelper.coerceKeyForObject': { 'name': 'Spah.SpahQL.DataHelper.coerceKeyForObject', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/coerceKeyForObject/index.html' },
'Spah.SpahQL.DataHelper.ltSet': { 'name': 'Spah.SpahQL.DataHelper.ltSet', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/ltSet/index.html' },
'Spah.SpahQL.DataHelper.jointSet': { 'name': 'Spah.SpahQL.DataHelper.jointSet', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/jointSet/index.html' },
'Spah.SpahQL.Callbacks.callbacksForPathInObject': { 'name': 'Spah.SpahQL.Callbacks.callbacksForPathInObject', 'type': 'class method', 'path': 'Spah/SpahQL/Callbacks/callbacksForPathInObject/index.html' },
'Spah.SpahQL.QueryRunner.assert': { 'name': 'Spah.SpahQL.QueryRunner.assert', 'type': 'class method', 'path': 'Spah/SpahQL/QueryRunner/assert/index.html' },
'Spah.SpahQL.Errors.SpahQLError': { 'name': 'Spah.SpahQL.Errors.SpahQLError', 'type': 'class', 'path': 'Spah/SpahQL/Errors/SpahQLError/index.html' },
'Spah.createServer': { 'name': 'Spah.createServer', 'type': 'class method', 'path': 'Spah/createServer/index.html' },
'Spah.SpahQL#item': { 'name': 'Spah.SpahQL#item', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/item/index.html' },
'Spah.createClient': { 'name': 'Spah.createClient', 'type': 'class method', 'path': 'Spah/createClient/index.html' },
'Spah.SpahQL.select': { 'name': 'Spah.SpahQL.select', 'type': 'class method', 'path': 'Spah/SpahQL/select/index.html' },
'Spah.SpahQL.Token.Numeric.parseAt': { 'name': 'Spah.SpahQL.Token.Numeric.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/Numeric/parseAt/index.html' },
'Spah.SpahQL.Token.ComparisonOperator': { 'name': 'Spah.SpahQL.Token.ComparisonOperator', 'type': 'class', 'path': 'Spah/SpahQL/Token/ComparisonOperator/index.html' },
'Spah.SpahQL.DataHelper.eqNumberRough': { 'name': 'Spah.SpahQL.DataHelper.eqNumberRough', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/eqNumberRough/index.html' },
'Spah.SpahQL#deleteAll': { 'name': 'Spah.SpahQL#deleteAll', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/deleteAll/index.html' },
'Spah.SpahQL#first': { 'name': 'Spah.SpahQL#first', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/first/index.html' },
'Spah.classRegister': { 'name': 'Spah.classRegister', 'type': 'class method', 'path': 'Spah/classRegister/index.html' },
'Spah.SpahQL.DataHelper.mathGte': { 'name': 'Spah.SpahQL.DataHelper.mathGte', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/mathGte/index.html' },
'new Spah.SpahQL.Token.Set': { 'name': 'new Spah.SpahQL.Token.Set', 'type': 'constructor', 'path': 'Spah/SpahQL/Token/Set/new/index.html' },
'Spah.SpahQL#concat': { 'name': 'Spah.SpahQL#concat', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/concat/index.html' },
'Spah.DOM.Document#run': { 'name': 'Spah.DOM.Document#run', 'type': 'instance method', 'path': 'Spah/DOM/Document/prototype/run/index.html' },
'Spah.State.Strategies': { 'name': 'Spah.State.Strategies', 'type': 'class', 'path': 'Spah/State/Strategies/index.html' },
'Spah.logMessages': { 'name': 'Spah.logMessages', 'type': 'class property', 'path': 'Spah/logMessages/index.html' },
'Spah.DOM.Blueprint#render': { 'name': 'Spah.DOM.Blueprint#render', 'type': 'instance method', 'path': 'Spah/DOM/Blueprint/prototype/render/index.html' },
'Spah.DOM.Modifiers.Show.down': { 'name': 'Spah.DOM.Modifiers.Show.down', 'type': 'class method', 'path': 'Spah/DOM/Modifiers/Show/down/index.html' },
'Spah.SpahQL#assert': { 'name': 'Spah.SpahQL#assert', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/assert/index.html' },
'Spah.StateClient#reduceCurrentState': { 'name': 'Spah.StateClient#reduceCurrentState', 'type': 'instance method', 'path': 'Spah/StateClient/prototype/reduceCurrentState/index.html' },
'Spah.StateClient': { 'name': 'Spah.StateClient', 'type': 'class', 'path': 'Spah/StateClient/index.html' },
'Spah.SpahQL.Token.parseAt': { 'name': 'Spah.SpahQL.Token.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/parseAt/index.html' },
'Spah.DOM.Document#runElementSync': { 'name': 'Spah.DOM.Document#runElementSync', 'type': 'instance method', 'path': 'Spah/DOM/Document/prototype/runElementSync/index.html' },
'Spah.DOM.Document': { 'name': 'Spah.DOM.Document', 'type': 'class', 'path': 'Spah/DOM/Document/index.html' },
'Spah.SpahQL.Token.PathComponent#filterQueries': { 'name': 'Spah.SpahQL.Token.PathComponent#filterQueries', 'type': 'instance property', 'path': 'Spah/SpahQL/Token/PathComponent/prototype/filterQueries/index.html' },
'Spah.SpahQL.Token.SelectionQuery.parseAt': { 'name': 'Spah.SpahQL.Token.SelectionQuery.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/SelectionQuery/parseAt/index.html' },
'Spah.SpahQL#replace': { 'name': 'Spah.SpahQL#replace', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/replace/index.html' },
'Spah.SpahQL.Query#rawString': { 'name': 'Spah.SpahQL.Query#rawString', 'type': 'instance property', 'path': 'Spah/SpahQL/Query/prototype/rawString/index.html' },
'Spah.SpahQL.DataHelper.mathCompare': { 'name': 'Spah.SpahQL.DataHelper.mathCompare', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/mathCompare/index.html' },
'Spah.SpahQL#detach': { 'name': 'Spah.SpahQL#detach', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/detach/index.html' },
'Spah.SpahQL.Token.SelectionQuery': { 'name': 'Spah.SpahQL.Token.SelectionQuery', 'type': 'class', 'path': 'Spah/SpahQL/Token/SelectionQuery/index.html' },
'Spah.SpahQL.Query': { 'name': 'Spah.SpahQL.Query', 'type': 'class', 'path': 'Spah/SpahQL/Query/index.html' },
'Spah.SpahQL#listen': { 'name': 'Spah.SpahQL#listen', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/listen/index.html' },
'Spah.SpahQL.Token.Set#evaluate': { 'name': 'Spah.SpahQL.Token.Set#evaluate', 'type': 'instance method', 'path': 'Spah/SpahQL/Token/Set/prototype/evaluate/index.html' },
'Spah.SpahQL.Token': { 'name': 'Spah.SpahQL.Token', 'type': 'class', 'path': 'Spah/SpahQL/Token/index.html' },
'Spah.SpahQL.Query#comparisonOperator': { 'name': 'Spah.SpahQL.Query#comparisonOperator', 'type': 'instance property', 'path': 'Spah/SpahQL/Query/prototype/comparisonOperator/index.html' },
'Spah.SpahQL.DataHelper.eqRough': { 'name': 'Spah.SpahQL.DataHelper.eqRough', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/eqRough/index.html' },
'Spah.SpahQL#select': { 'name': 'Spah.SpahQL#select', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/select/index.html' },
'Spah.SpahQL.DataHelper.hashKeys': { 'name': 'Spah.SpahQL.DataHelper.hashKeys', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/hashKeys/index.html' },
'Spah.StateServer#identifyStateFromRequest': { 'name': 'Spah.StateServer#identifyStateFromRequest', 'type': 'instance method', 'path': 'Spah/StateServer/prototype/identifyStateFromRequest/index.html' },
'Spah.SpahQL#sourceData': { 'name': 'Spah.SpahQL#sourceData', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/sourceData/index.html' },
'Spah.SpahQL#keyNames': { 'name': 'Spah.SpahQL#keyNames', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/keyNames/index.html' },
'Spah.DOM.Modifiers': { 'name': 'Spah.DOM.Modifiers', 'type': 'class', 'path': 'Spah/DOM/Modifiers/index.html' },
'Spah.DOM.Blueprint': { 'name': 'Spah.DOM.Blueprint', 'type': 'class', 'path': 'Spah/DOM/Blueprint/index.html' },
'Spah.DOM': { 'name': 'Spah.DOM', 'type': 'class', 'path': 'Spah/DOM/index.html' },
'Spah.State.Strategies.keeper': { 'name': 'Spah.State.Strategies.keeper', 'type': 'class method', 'path': 'Spah/State/Strategies/keeper/index.html' },
'Spah.SpahQL#unlisten': { 'name': 'Spah.SpahQL#unlisten', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/unlisten/index.html' },
'Spah.SpahQL.Token.Boolean.parseAt': { 'name': 'Spah.SpahQL.Token.Boolean.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/Boolean/parseAt/index.html' },
'Spah.SpahQL.DataHelper.modificationSymbol': { 'name': 'Spah.SpahQL.DataHelper.modificationSymbol', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/modificationSymbol/index.html' },
'Spah.SpahQL.result': { 'name': 'Spah.SpahQL.result', 'type': 'class method', 'path': 'Spah/SpahQL/result/index.html' },
'Spah.log': { 'name': 'Spah.log', 'type': 'class method', 'path': 'Spah/log/index.html' },
'Spah.DOM.Modifiers.ElementId': { 'name': 'Spah.DOM.Modifiers.ElementId', 'type': 'class', 'path': 'Spah/DOM/Modifiers/ElementId/index.html' },
'Spah.SpahQL#containingAll': { 'name': 'Spah.SpahQL#containingAll', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/containingAll/index.html' },
'Spah.DOM.Modifiers.Show.up': { 'name': 'Spah.DOM.Modifiers.Show.up', 'type': 'class method', 'path': 'Spah/DOM/Modifiers/Show/up/index.html' },
'Spah.DOM.Document#runSync': { 'name': 'Spah.DOM.Document#runSync', 'type': 'instance method', 'path': 'Spah/DOM/Document/prototype/runSync/index.html' },
'Spah.SpahQL.DataHelper.truthySet': { 'name': 'Spah.SpahQL.DataHelper.truthySet', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/truthySet/index.html' },
'Spah.SpahQL.DataHelper.mathLt': { 'name': 'Spah.SpahQL.DataHelper.mathLt', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/mathLt/index.html' },
'Spah.SpahQL#parent': { 'name': 'Spah.SpahQL#parent', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/parent/index.html' },
'Spah.SpahQL.Token.KeyName.parseAt': { 'name': 'Spah.SpahQL.Token.KeyName.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/KeyName/parseAt/index.html' },
'Spah.DOM.Document#removeTemplate': { 'name': 'Spah.DOM.Document#removeTemplate', 'type': 'instance method', 'path': 'Spah/DOM/Document/prototype/removeTemplate/index.html' },
'Spah.SpahQL#filter': { 'name': 'Spah.SpahQL#filter', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/filter/index.html' },
'Spah.SpahQL.Token.Set#isRange': { 'name': 'Spah.SpahQL.Token.Set#isRange', 'type': 'instance property', 'path': 'Spah/SpahQL/Token/Set/prototype/isRange/index.html' },
'Spah.SpahQL#path': { 'name': 'Spah.SpahQL#path', 'type': 'instance method', 'path': 'Spah/SpahQL/prototype/path/index.html' },
'Spah.SpahQL.Token.Set#tokens': { 'name': 'Spah.SpahQL.Token.Set#tokens', 'type': 'instance property', 'path': 'Spah/SpahQL/Token/Set/prototype/tokens/index.html' },
'new Spah.DOM.Document': { 'name': 'new Spah.DOM.Document', 'type': 'constructor', 'path': 'Spah/DOM/Document/new/index.html' },
'Spah.SpahQL.Strategiser': { 'name': 'Spah.SpahQL.Strategiser', 'type': 'class', 'path': 'Spah/SpahQL/Strategiser/index.html' },
'Spah.SpahQL.DataHelper.eqStringRough': { 'name': 'Spah.SpahQL.DataHelper.eqStringRough', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/eqStringRough/index.html' },
'Spah.SpahQL.DataHelper.eq': { 'name': 'Spah.SpahQL.DataHelper.eq', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/eq/index.html' },
'Spah.SpahQL.Token.PathComponent#fetchResultsFromObjectByProperty': { 'name': 'Spah.SpahQL.Token.PathComponent#fetchResultsFromObjectByProperty', 'type': 'instance method', 'path': 'Spah/SpahQL/Token/PathComponent/prototype/fetchResultsFromObjectByProperty/index.html' },
'Spah.SpahQL.Token.FilterQuery': { 'name': 'Spah.SpahQL.Token.FilterQuery', 'type': 'class', 'path': 'Spah/SpahQL/Token/FilterQuery/index.html' },
'Spah.DOM.Modifiers.ElementId.actionName': { 'name': 'Spah.DOM.Modifiers.ElementId.actionName', 'type': 'class method', 'path': 'Spah/DOM/Modifiers/ElementId/actionName/index.html' }
};