module Spah
  module SpahQL
    module Token
      
      # A superclass wrapping all tokens that may be generated by the query parser during parsing.
      # All subclasses are expected to implement a class method parse_at(index, string) which
      # reads ahead and identifies the token, returning a tuple of the terminating index for the found token
      # and the token itself, or nil if the token was not identified at the given index.
      class Base
        
        # Never ever use this. You did not see this.
        def self.parse_at(i, query)
          raise "override me"
        end
        
      end
      
    end
  end
end