---
id: "Spah.SpahQL.Query"
parent_id: "Spah.SpahQL"
type: class
line_number: 7
description: |
  A <code>Query</code> instance is the result of running a string state query such as "/foo/bar/baz == 1" through the <code>Spah.SpahQL.QueryParser</code>.
  Queries are parsed only once, upon registration. The QueryParser maintains a cache of pre-existing parsed queries keyed by the original query string.

file: /home/danski/projects/spah/src/Spah.SpahQL.Query.js

---
id: "Spah.SpahQL.Query#rawString"
parent_id: "Spah.SpahQL.Query"
type: instance property
line_number: 21
description: |
  The string from which this query was originally parsed.

signatures:
 -
  signature: "Spah.SpahQL.Query#rawString"
  return_value: "String original representation"
file: /home/danski/projects/spah/src/Spah.SpahQL.Query.js

---
id: "Spah.SpahQL.Query#primaryToken"
parent_id: "Spah.SpahQL.Query"
type: instance property
line_number: 28
description: |
  The first (non-optional) token in the query.

signatures:
 -
  signature: "Spah.SpahQL.Query#primaryToken"
  return_value: "Primary token (set literal or selection query)"
file: /home/danski/projects/spah/src/Spah.SpahQL.Query.js

---
id: "Spah.SpahQL.Query#comparisonOperator"
parent_id: "Spah.SpahQL.Query"
type: instance property
line_number: 36
description: |
  The optional comparison operator. If this is set, the query is an assertion query and there must
  be a secondary token defined.

signatures:
 -
  signature: "Spah.SpahQL.Query#comparisonOperator"
  return_value: "String comparison operator"
file: /home/danski/projects/spah/src/Spah.SpahQL.Query.js

---
id: "Spah.SpahQL.Query#secondaryToken"
parent_id: "Spah.SpahQL.Query"
type: instance property
line_number: 43
description: |
  The second (optional) token in the query. Cannot be defined without a comparison operator.

signatures:
 -
  signature: "Spah.SpahQL.Query#secondaryToken"
  return_value: "Secondary token (set literal or selection query)"
file: /home/danski/projects/spah/src/Spah.SpahQL.Query.js

---
id: "Spah.SpahQL.Query#assertion"
parent_id: "Spah.SpahQL.Query"
type: instance property
line_number: 50
description: |
  Set to <code>true</code> if the query is an assertion query.

signatures:
 -
  signature: "Spah.SpahQL.Query#assertion"
  return_value: "Boolean assertion flag"
file: /home/danski/projects/spah/src/Spah.SpahQL.Query.js