---
id: "Spah.State"
parent_id: "Spah"
type: class
line_number: 8
description: |
  Spah.State is the wrapping class for the <code>state</code> defined by your application.
  It supports querying and assertions against the state and is also responsible for deep-merging
  state updates from the server and dispatching modification events to your responders.

file: /Users/danski/Sites/spah/src/Spah.State.js

---
id: "new Spah.State"
parent_id: "Spah.State"
type: constructor
line_number: 29
description: |
  - data (Object): A hash of data to act as the starting state. Note that modification events are not fired during instantiation.

signatures:
 -
  signature: "new Spah.State(data)"
file: /Users/danski/Sites/spah/src/Spah.State.js

---
id: "Spah.State#data"
parent_id: "Spah.State"
type: instance property
line_number: 39
description: |
  The raw JSON construct being managed by this Spah.State instance. If you overwrite this directly,
  you will be haunted by a pigeon.

signatures:
 -
  signature: "Spah.State#data"
  return_value: "Object"
file: /Users/danski/Sites/spah/src/Spah.State.js

---
id: "Spah.State#update"
parent_id: "Spah.State"
type: instance method
line_number: 59
description: |
  Deep-merges a hash of state changes into the current state:
  
       myState.data //-> {foo: {chicken: "bkawk", cow: "mooo", cat: "meow"}}
       myState.update({
         foo: {
           chicken: "hello i am a chicken nice to meet you",
           owl: "hoot",
           cat: null,
         }
       })
       //-> {"/foo": "~", "/foo/chicken": "~", "/foo/owl": "+", "/foo/cat": "-"}
  
  During the merge hashes are merged, while strings, arrays and booleans are replaced if re-specified in the delta.

signatures:
 -
  signature: "Spah.State#update(delta)"
  return_value: "Object hash of path modifications"
arguments:
 -
  name: delta
  types: [Object]
  description: >
    a hash to be deep-merged into the existing data construct. Deep merging always occurs at the root of the existing state.

file: /Users/danski/Sites/spah/src/Spah.State.js