---
id: "Spah.SpahQL.Token.PathComponent"
parent_id: "Spah.SpahQL.Token"
type: class
superclass_id: "Spah.SpahQL.Token.Base"
line_number: 7
description: |
  A token describing any path component within a selection query, comprised of one or two path delimiters
  followed by a key or property name and an optional set of filter query tokens.

file: /home/danski/projects/spah/src/Spah.SpahQL.Token.PathComponent.js

---
id: "Spah.SpahQL.Token.PathComponent.parseAt"
parent_id: "Spah.SpahQL.Token.PathComponent"
type: class method
line_number: 25
description: |
  Reads the given queryString starting at the given index and attempts to identify and parse
  a path component token. If found, the token will be returned in a tuple \[resumeIndex, foundToken\].
  Returns null if nothing is found.

signatures:
 -
  signature: "Spah.SpahQL.Token.PathComponent.parseAt(index, queryString)"
  return_value: "Array result or null"
file: /home/danski/projects/spah/src/Spah.SpahQL.Token.PathComponent.js

---
id: "Spah.SpahQL.Token.PathComponent#key"
parent_id: "Spah.SpahQL.Token.PathComponent"
type: instance property
line_number: 94
description: |
  The key specified in this path component, if a keyname was used.

signatures:
 -
  signature: "Spah.SpahQL.Token.PathComponent#key"
  return_value: "String"
file: /home/danski/projects/spah/src/Spah.SpahQL.Token.PathComponent.js

---
id: "Spah.SpahQL.Token.PathComponent#property"
parent_id: "Spah.SpahQL.Token.PathComponent"
type: instance property
line_number: 101
description: |
  The property specified in this path component, if a property name was used.

signatures:
 -
  signature: "Spah.SpahQL.Token.PathComponent#property"
  return_value: "String"
file: /home/danski/projects/spah/src/Spah.SpahQL.Token.PathComponent.js

---
id: "Spah.SpahQL.Token.PathComponent#recursive"
parent_id: "Spah.SpahQL.Token.PathComponent"
type: instance property
line_number: 109
description: |
  A flag indicating whether or not this path component should recurse through its
  scope data during evaluation.

signatures:
 -
  signature: "Spah.SpahQL.Token.PathComponent#recursive"
  return_value: "Boolean"
file: /home/danski/projects/spah/src/Spah.SpahQL.Token.PathComponent.js

---
id: "Spah.SpahQL.Token.PathComponent#filterQueries"
parent_id: "Spah.SpahQL.Token.PathComponent"
type: instance property
line_number: 117
description: |
  Lists all filter queries associated with this path component, in the order in which they were
  encountered during parsing.

signatures:
 -
  signature: "Spah.SpahQL.Token.PathComponent#filterQueries"
  return_value: "Array Token.FilterQuery"
file: /home/danski/projects/spah/src/Spah.SpahQL.Token.PathComponent.js

---
id: "new Spah.SpahQL.Token.PathComponent"
parent_id: "Spah.SpahQL.Token.PathComponent"
type: constructor
line_number: 124
description: |
  Instantiate a path component token with blank-slate values

signatures:
 -
  signature: "new Spah.SpahQL.Token.PathComponent(key, property, recursive, filterQueries)"
file: /home/danski/projects/spah/src/Spah.SpahQL.Token.PathComponent.js

---
id: "Spah.SpahQL.Token.PathComponent#evaluate"
parent_id: "Spah.SpahQL.Token.PathComponent"
type: instance method
line_number: 142
description: |
  Evaluates this path pomponent and returns a set of query results.
  Used primarily in Token.SelectionQuery#evaluate to map each path component to a set of results, allowing the query process to be
  effectively forked or halted.

signatures:
 -
  signature: "Spah.SpahQL.Token.PathComponent#evaluate(rootData, scopeData, path)"
  return_value: "Array"
arguments:
 -
  name: pathComponent
  types: [Object]
  description: >
    A path component object as generated by the query parser

 -
  name: rootData
  types: [Object]
  description: >
    The entire root-level data structure being queried

 -
  name: scopeData
  types: [Object]
  description: >
    The data for the scope at which this query is being executed.

 -
  name: path
  types: [String]
  description: >
    The string path for the root of the scopeData argument.

file: /home/danski/projects/spah/src/Spah.SpahQL.Token.PathComponent.js

---
id: "Spah.SpahQL.Token.PathComponent#fetchResultsFromObjectByKey"
parent_id: "Spah.SpahQL.Token.PathComponent"
type: instance method
line_number: 198
description: |
  Retrieves the value(s) associated with a given key from the given object, if such a key exists.

signatures:
 -
  signature: "Spah.SpahQL.Token.PathComponent#fetchResultsFromObjectByKey(key, object, path, recursive)"
  return_value: "Array"
arguments:
 -
  name: key
  types: [String]
  description: >
    The key to be retrieved from the object. Numeric keys in string formare acceptable when accessing arrays.]

 -
  name: rootData
  types: [Object]
  description: >
    The root data structure being queried.

 -
  name: scopeData
  types: [Object]
  description: >
    The data structure from which the key's associated value will be retrieved

 -
  name: path
  types: [String]
  description: >
    The path at which the item used as the 'object' argument is located

 -
  name: recursive
  types: [Boolean]
  description: >
    A flag indicating whether the key should also be pulled from any child objects of the given object. I N C E P T I O N.

file: /home/danski/projects/spah/src/Spah.SpahQL.Token.PathComponent.js

---
id: "Spah.SpahQL.Token.PathComponent#fetchResultsFromObjectByProperty"
parent_id: "Spah.SpahQL.Token.PathComponent"
type: instance method
line_number: 232
description: |
  Retrieves the specified Spah object property from the given object, if the object supports the specified property.

signatures:
 -
  signature: "Spah.SpahQL.Token.PathComponent#fetchResultsFromObjectByProperty(key, object, path, recursive)"
  return_value: "Array"
arguments:
 -
  name: key
  types: [String]
  description: >
    The key to be retrieved from the object. Numeric keys in string formare acceptable when accessing arrays.

 -
  name: rootData
  types: [Object]
  description: >
    The root data structure being queried.

 -
  name: scopeData
  types: [Object]
  description: >
    The data structure from which the key's associated value will be retrieved

 -
  name: path
  types: [String]
  description: >
    The path at which the item used as the 'object' argument is located

 -
  name: recursive
  types: [Boolean]
  description: >
    A flag indicating whether the key should also be pulled from any child objects of the given object. I N C E P T I O N.

file: /home/danski/projects/spah/src/Spah.SpahQL.Token.PathComponent.js