---
id: "Spah.Document.Modifiers"
parent_id: "Spah.Document"
type: class
line_number: 11
description: |
  An instance of <code>Modifiers</code> exists on every instance of <code>Spah.Document</code>.
  The <code>Modifiers</code> instance acts as a router for applying helper code such as stashing, classnames and
  any other document modification to elements.
  
  You may add your own helpers to Spah, or disable helpers that you don't need. See #add and #remove for details.
  Each instance of <code>Modifiers</code> registers the default helpers on creation.

file: /Users/danski/Sites/spah/src/Spah.Document.Modifiers.js

---
id: "Spah.Document.Modifiers#modules"
parent_id: "Spah.Document.Modifiers"
type: instance property
line_number: 27
description: |
  The list of registered modifications.

signatures:
 -
  signature: "Spah.Document.Modifiers#modules"
  return_value: "Array"
file: /Users/danski/Sites/spah/src/Spah.Document.Modifiers.js

---
id: "new Spah.Document.Modifiers"
parent_id: "Spah.Document.Modifiers"
type: constructor
line_number: 35
description: |
  Initialises a new <code>Modifiers</code> router for use on a document, with the default helpers
  already registered. See #defaults for details of the default helpers.

signatures:
 -
  signature: "new Spah.Document.Modifiers()"
file: /Users/danski/Sites/spah/src/Spah.Document.Modifiers.js

---
id: "Spah.Document.Modifiers#add"
parent_id: "Spah.Document.Modifiers"
type: instance method
line_number: 52
description: |
  Registers a modifier module, which must be an object implementing the functions:
  - **responds(attributeName)** Returns a boolean indicating whether or not this module will respond to the found attribute.
  - **up(element, state)** Runs the modification forwards. Used when the associated assertion flips from false to true for _if_ assertions and when the associated assertion flips from true to false for _unless_ assertions.
  - **down(element, state)** Runs the modification backwards. Called when the associated assertion flips from true to false for _if_ assertions and when the associated assertion flips from false to true for _unless_ assertions.

signatures:
 -
  signature: "Spah.Document.Modifiers#add(module)"
  return_value: "Boolean"
arguments:
 -
  name: module
  types: [Object]
  description: >
    The module to be registered. Expected to implement the module interface.

file: /Users/danski/Sites/spah/src/Spah.Document.Modifiers.js