---
id: "Spah.SpahQL.Token.Boolean"
parent_id: "Spah.SpahQL.Token"
type: class
superclass_id: "Spah.SpahQL.Token.Simple"
line_number: 6
description: |
  A simple token wrapping a boolean true or false.

file: /Users/danski/Sites/spah/src/Spah.SpahQL.Token.Boolean.js

---
id: "Spah.SpahQL.Token.Boolean.parseAt"
parent_id: "Spah.SpahQL.Token.Boolean"
type: class method
line_number: 19
description: |
  Identifies a boolean true or false at the given index in the given string query and returns null
  if no token is identified, or a tuple of terminating index and the instantiated token if successful.

signatures:
 -
  signature: "Spah.SpahQL.Token.Boolean.parseAt(i, query)"
  return_value: "Array\\[resumeIndex, foundToken\\] or null"
file: /Users/danski/Sites/spah/src/Spah.SpahQL.Token.Boolean.js