---
id: "Spah.SpahQL.QueryParser"
parent_id: "Spah.SpahQL"
type: class
line_number: 7
description: |
  Parses string queries from data-\*-if attributes and client-side responders and produces parsed <code>Spah.SpahQL.Query</code> instances.
  Maintains a cache of previously-parsed queries for speed.

file: /Users/danski/Sites/spah/src/Spah.SpahQL.QueryParser.js

---
id: "Spah.SpahQL.QueryParser.queryCache"
parent_id: "Spah.SpahQL.QueryParser"
type: class property
line_number: 17
description: |
  Holds a cache of previously-parsed queries indexed by string representation.

signatures:
 -
  signature: "Spah.SpahQL.QueryParser.queryCache"
  return_value: "Object cached queries"
file: /Users/danski/Sites/spah/src/Spah.SpahQL.QueryParser.js

---
id: "Spah.SpahQL.QueryParser.parseQuery"
parent_id: "Spah.SpahQL.QueryParser"
type: class method
line_number: 31
description: |
  Parses a string query and returns a parsed <code>Spah.SpahQL.Query</code> instance.
  
  Uses control characters such as set openers, comparison operators and path delimiters to throw the
  tokenizer into a variety of states. The actual parsing of each token is handed by a set of functions
  with naming convention readAhead, e.g. <code>readAheadStringLiteral</code>. These methods are
  responsible for identifying the token, reading ahead to parse it, and returning the found object
  to the tokenizer along with an updated index at which the tokenizer may resume parsing.

signatures:
 -
  signature: "Spah.SpahQL.QueryParser.parseQuery(str)"
  return_value: "Spah.SpahQL.Query instance"
arguments:
 -
  name: str
  types: [String]
  description: >
    The string query e.g. "/foo/bar == 3"

file: /Users/danski/Sites/spah/src/Spah.SpahQL.QueryParser.js

---
id: "Spah.SpahQL.QueryParser.throwParseErrorAt"
parent_id: "Spah.SpahQL.QueryParser"
type: class method
line_number: 98
description: |
  Throws an exception at the given index in the given query string with the given error message.

signatures:
 -
  signature: "Spah.SpahQL.QueryParser.throwParseErrorAt(i, query, message)"
  return_value: "void"
file: /Users/danski/Sites/spah/src/Spah.SpahQL.QueryParser.js