---
id: "Spah.SpahQL.QueryResultSet"
parent_id: "Spah.SpahQL"
type: class
line_number: 6
description: |
  Wraps an array of QueryResult objects and provides manipulation and traversal methods upon the set.

file: /Users/danski/Sites/spah/src/Spah.SpahQL.QueryResultSet.js

---
id: "new Spah.SpahQL.QueryResultSet"
parent_id: "Spah.SpahQL.QueryResultSet"
type: constructor
line_number: 22
description: |
  Creates a new resultset from an array of QueryResult objects

signatures:
 -
  signature: "new Spah.SpahQL.QueryResultSet(results)"
arguments:
 -
  name: results
  types: [Array]
  description: >
    An array of query result objects.

file: /Users/danski/Sites/spah/src/Spah.SpahQL.QueryResultSet.js

---
id: "Spah.SpahQL.QueryResultSet#all"
parent_id: "Spah.SpahQL.QueryResultSet"
type: instance method
line_number: 31
description: |
  Returns all items in the result set.

signatures:
 -
  signature: "Spah.SpahQL.QueryResultSet#all()"
  return_value: "Array of Spah.SpahQL.QueryResult objects"
file: /Users/danski/Sites/spah/src/Spah.SpahQL.QueryResultSet.js

---
id: "Spah.SpahQL.QueryResultSet#all"
parent_id: "Spah.SpahQL.QueryResultSet"
type: instance method
line_number: 40
description: |
  Returns the first item in the result set.

signatures:
 -
  signature: "Spah.SpahQL.QueryResultSet#all()"
  return_value: "null, Spah.SpahQL.QueryResult"
file: /Users/danski/Sites/spah/src/Spah.SpahQL.QueryResultSet.js

---
id: "Spah.SpahQL.QueryResultSet#item"
parent_id: "Spah.SpahQL.QueryResultSet"
type: instance method
line_number: 49
description: |
  Returns the item in the result set at the given index, or null.

signatures:
 -
  signature: "Spah.SpahQL.QueryResultSet#item(index)"
  return_value: "null, Spah.SpahQL.QueryResult"
file: /Users/danski/Sites/spah/src/Spah.SpahQL.QueryResultSet.js

---
id: "Spah.SpahQL.QueryResultSet#length"
parent_id: "Spah.SpahQL.QueryResultSet"
type: instance method
line_number: 58
description: |
  Returns the number of results in this resultset.

signatures:
 -
  signature: "Spah.SpahQL.QueryResultSet#length()"
  return_value: "Integer"
file: /Users/danski/Sites/spah/src/Spah.SpahQL.QueryResultSet.js

---
id: "Spah.SpahQL.QueryResultSet#each"
parent_id: "Spah.SpahQL.QueryResultSet"
type: instance method
line_number: 72
description: |
  Executes the callback function with each item in this resultset. The
  loop is halted if the callback at any time returns false. This method will
  return true if the loop completes, and false if it is halted midway. If the callback
  function does not return anything, the loop will continue to completion.

signatures:
 -
  signature: "Spah.SpahQL.QueryResultSet#each(callback)"
  return_value: "Boolean"
arguments:
 -
  name: callback
  types: [Function]
  description: >
    A callback to execute against each result in the set. The callback will receive the arguments (index, total). within the function, the <code>this</code> keyword will refer to the QueryResult for this iteration.

file: /Users/danski/Sites/spah/src/Spah.SpahQL.QueryResultSet.js

---
id: "Spah.SpahQL.QueryResultSet#map"
parent_id: "Spah.SpahQL.QueryResultSet"
type: instance method
line_number: 87
description: |
  Executes the callback function with each item in this resultset. The return value from
  each iteration of the callback is appended to an array, which is returned at the end of the loop.

signatures:
 -
  signature: "Spah.SpahQL.QueryResultSet#map(callback)"
  return_value: "Array"
arguments:
 -
  name: callback
  types: [Function]
  description: >
    A callback to execute against each result in the set. The callback will receive the arguments (result, index, total), within the function, the <code>this</code> keyword will refer to the QueryResult for this iteration.

file: /Users/danski/Sites/spah/src/Spah.SpahQL.QueryResultSet.js

---
id: "Spah.SpahQL.QueryResultSet#parentPath"
parent_id: "Spah.SpahQL.QueryResultSet"
type: instance method
line_number: 100
description: |
  Retrieves the parent path for the first item in this resultset.

signatures:
 -
  signature: "Spah.SpahQL.QueryResultSet#parentPath()"
  return_value: "null or String"
file: /Users/danski/Sites/spah/src/Spah.SpahQL.QueryResultSet.js

---
id: "Spah.SpahQL.QueryResultSet#parent"
parent_id: "Spah.SpahQL.QueryResultSet"
type: instance method
line_number: 110
description: |
  Retrieves the parent object for the first item in this resultset.

signatures:
 -
  signature: "Spah.SpahQL.QueryResultSet#parent()"
  return_value: "null or QueryResult"
file: /Users/danski/Sites/spah/src/Spah.SpahQL.QueryResultSet.js

---
id: "Spah.SpahQL.QueryResultSet#select"
parent_id: "Spah.SpahQL.QueryResultSet"
type: instance method
line_number: 122
description: |
  Executes a scoped selection query for each result in the set,
  and compresses the results into a single resultset made unique by result path.

signatures:
 -
  signature: "Spah.SpahQL.QueryResultSet#select(query)"
  return_value: "QueryResultSet"
arguments:
 -
  name: query
  types: [String]
  description: >
    The query to be executed.

file: /Users/danski/Sites/spah/src/Spah.SpahQL.QueryResultSet.js

---
id: "Spah.SpahQL.QueryResultSet#assert"
parent_id: "Spah.SpahQL.QueryResultSet"
type: instance method
line_number: 148
description: |
  Executes a scoped assertion query for each result in the set,
  returning true if all results are successfully asserted and false
  if any result fails to be asserted.

signatures:
 -
  signature: "Spah.SpahQL.QueryResultSet#assert(query)"
  return_value: "Boolean"
arguments:
 -
  name: query
  types: [String]
  description: >
    The assertion query to be executed.

file: /Users/danski/Sites/spah/src/Spah.SpahQL.QueryResultSet.js

---
id: "Spah.SpahQL.QueryResultSet#set"
parent_id: "Spah.SpahQL.QueryResultSet"
type: instance method
line_number: 162
description: |
  - key (Integer, String): The that you want to set.
  - value (String): The value to which you want that key set.
  
  Calls set(key, value) on the first result in this result set and returns
  the boolean response.

signatures:
 -
  signature: "Spah.SpahQL.QueryResultSet#set(key, value)"
  return_value: "Boolean"
file: /Users/danski/Sites/spah/src/Spah.SpahQL.QueryResultSet.js

---
id: "Spah.SpahQL.QueryResultSet#replace"
parent_id: "Spah.SpahQL.QueryResultSet"
type: instance method
line_number: 174
description: |
  Calls replace(value) on the first result in this result set and returns
  the boolean response.

signatures:
 -
  signature: "Spah.SpahQL.QueryResultSet#replace(value)"
  return_value: "Boolean"
arguments:
 -
  name: value
  types: [Object]
  description: >
    The value to replace the first result in this set.

file: /Users/danski/Sites/spah/src/Spah.SpahQL.QueryResultSet.js

---
id: "Spah.SpahQL.QueryResultSet#replaceAll"
parent_id: "Spah.SpahQL.QueryResultSet"
type: instance method
line_number: 186
description: |
  Calls replace(value) on each result in this result set and returns
  the set with values altered where possible.

signatures:
 -
  signature: "Spah.SpahQL.QueryResultSet#replaceAll(value)"
  return_value: "QueryResultSet"
arguments:
 -
  name: value
  types: [Object]
  description: >
    The value to replace all results in this set.

file: /Users/danski/Sites/spah/src/Spah.SpahQL.QueryResultSet.js

---
id: "Spah.SpahQL.QueryResultSet#replaceEach"
parent_id: "Spah.SpahQL.QueryResultSet"
type: instance method
line_number: 202
description: |
  Calls a test function for each result in this set in turn, and calls replace(value) on those results for which
  the test function returns <code>true</code>. Returns this set with the values modified.

signatures:
 -
  signature: "Spah.SpahQL.QueryResultSet#replaceEach(value, testCallback)"
  return_value: "QueryResultSet"
arguments:
 -
  name: value
  types: [Object]
  description: >
    The value to replace any results where the test function is passed.

 -
  name: testCallback
  types: [Function]
  description: >
    A function used to test each result in the set. The function will have the same scope and arguments as the callback used in #each.

file: /Users/danski/Sites/spah/src/Spah.SpahQL.QueryResultSet.js

---
id: "Spah.SpahQL.QueryResultSet#modified"
parent_id: "Spah.SpahQL.QueryResultSet"
type: instance method
line_number: 217
description: |
  Calls modified(callback) on every result in this set, registering the same callback function
  for modifications to every path represented in this result set.

signatures:
 -
  signature: "Spah.SpahQL.QueryResultSet#modified(callback)"
  return_value: "void"
file: /Users/danski/Sites/spah/src/Spah.SpahQL.QueryResultSet.js