---
id: "Spah.SpahQL.Token.String"
parent_id: "Spah.SpahQL.Token"
type: class
superclass_id: "Spah.SpahQL.Token.Simple"
line_number: 6
description: |
  A simple token wrapping a string literal value.

file: /home/danski/projects/spah/src/Spah.SpahQL.Token.String.js

---
id: "Spah.SpahQL.Token.String.parseAt"
parent_id: "Spah.SpahQL.Token.String"
type: class method
line_number: 23
description: |
  Identifies a string literal at the given index in the given string query and returns null
  if no token is identified, or a tuple of terminating index and the instantiated token if successful.

signatures:
 -
  signature: "Spah.SpahQL.Token.String.parseAt(i, query)"
  return_value: "Array\\[resumeIndex, foundToken\\] or null"
file: /home/danski/projects/spah/src/Spah.SpahQL.Token.String.js