if (!window.PDoc) window.PDoc = {};
PDoc.elements = {
  'Spah.SpahQL.Token.Simple': { 'name': 'Spah.SpahQL.Token.Simple', 'type': 'class', 'path': 'Spah/SpahQL/Token/Simple/index.html' },
'new Spah.SpahQL.Token.PathComponent': { 'name': 'new Spah.SpahQL.Token.PathComponent', 'type': 'constructor', 'path': 'Spah/SpahQL/Token/PathComponent/new/index.html' },
'Spah.SpahQL.QueryRunner.evalAssertion': { 'name': 'Spah.SpahQL.QueryRunner.evalAssertion', 'type': 'class method', 'path': 'Spah/SpahQL/QueryRunner/evalAssertion/index.html' },
'Spah.SpahQL.QueryRunner.select': { 'name': 'Spah.SpahQL.QueryRunner.select', 'type': 'class method', 'path': 'Spah/SpahQL/QueryRunner/select/index.html' },
'Spah.SpahQL.QueryResultSet#modified': { 'name': 'Spah.SpahQL.QueryResultSet#modified', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResultSet/prototype/modified/index.html' },
'Spah.SpahQL.Errors': { 'name': 'Spah.SpahQL.Errors', 'type': 'class', 'path': 'Spah/SpahQL/Errors/index.html' },
'Spah.DOM.Modifiers#modifierChainForElement': { 'name': 'Spah.DOM.Modifiers#modifierChainForElement', 'type': 'instance method', 'path': 'Spah/DOM/Modifiers/prototype/modifierChainForElement/index.html' },
'new Spah.SpahQL.Token.SelectionQuery': { 'name': 'new Spah.SpahQL.Token.SelectionQuery', 'type': 'constructor', 'path': 'Spah/SpahQL/Token/SelectionQuery/new/index.html' },
'Spah.SpahQL.QueryResultSet#parent': { 'name': 'Spah.SpahQL.QueryResultSet#parent', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResultSet/prototype/parent/index.html' },
'Spah.State#data': { 'name': 'Spah.State#data', 'type': 'instance property', 'path': 'Spah/State/prototype/data/index.html' },
'Spah.SpahQL.QueryResultSet#all': { 'name': 'Spah.SpahQL.QueryResultSet#all', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResultSet/prototype/all/index.html' },
'Spah.DOM.Modifiers': { 'name': 'Spah.DOM.Modifiers', 'type': 'class', 'path': 'Spah/DOM/Modifiers/index.html' },
'Spah.SpahQL.Token.Numeric.parseAt': { 'name': 'Spah.SpahQL.Token.Numeric.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/Numeric/parseAt/index.html' },
'Spah.SpahQL.QueryResult#assert': { 'name': 'Spah.SpahQL.QueryResult#assert', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResult/prototype/assert/index.html' },
'Spah.SpahQL.DataHelper.hashValues': { 'name': 'Spah.SpahQL.DataHelper.hashValues', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/hashValues/index.html' },
'Spah.SpahQL.DataHelper.superSet': { 'name': 'Spah.SpahQL.DataHelper.superSet', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/superSet/index.html' },
'new Spah.SpahQL.Token.Simple': { 'name': 'new Spah.SpahQL.Token.Simple', 'type': 'constructor', 'path': 'Spah/SpahQL/Token/Simple/new/index.html' },
'Spah.classCreate': { 'name': 'Spah.classCreate', 'type': 'class method', 'path': 'Spah/classCreate/index.html' },
'Spah.SpahQL.Token.ComparisonOperator': { 'name': 'Spah.SpahQL.Token.ComparisonOperator', 'type': 'class', 'path': 'Spah/SpahQL/Token/ComparisonOperator/index.html' },
'Spah.SpahQL.QueryResultSet#replaceEach': { 'name': 'Spah.SpahQL.QueryResultSet#replaceEach', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResultSet/prototype/replaceEach/index.html' },
'Spah.SpahQL.Query#comparisonOperator': { 'name': 'Spah.SpahQL.Query#comparisonOperator', 'type': 'instance property', 'path': 'Spah/SpahQL/Query/prototype/comparisonOperator/index.html' },
'Spah.SpahQL.Query#secondaryToken': { 'name': 'Spah.SpahQL.Query#secondaryToken', 'type': 'instance property', 'path': 'Spah/SpahQL/Query/prototype/secondaryToken/index.html' },
'Spah.SpahQL.Token.Set#evalNumericRange': { 'name': 'Spah.SpahQL.Token.Set#evalNumericRange', 'type': 'instance method', 'path': 'Spah/SpahQL/Token/Set/prototype/evalNumericRange/index.html' },
'Spah.SpahQL.DataHelper.ltSet': { 'name': 'Spah.SpahQL.DataHelper.ltSet', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/ltSet/index.html' },
'Spah.SpahQL.QueryResultSet#replaceAll': { 'name': 'Spah.SpahQL.QueryResultSet#replaceAll', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResultSet/prototype/replaceAll/index.html' },
'Spah.SpahQL.DataHelper': { 'name': 'Spah.SpahQL.DataHelper', 'type': 'class', 'path': 'Spah/SpahQL/DataHelper/index.html' },
'Spah.SpahQL.DataHelper.mathCompare': { 'name': 'Spah.SpahQL.DataHelper.mathCompare', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/mathCompare/index.html' },
'Spah.DOM.Document#run': { 'name': 'Spah.DOM.Document#run', 'type': 'instance method', 'path': 'Spah/DOM/Document/prototype/run/index.html' },
'Spah.SpahQL.DataHelper.jointSetWithCallback': { 'name': 'Spah.SpahQL.DataHelper.jointSetWithCallback', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/jointSetWithCallback/index.html' },
'Spah.SpahQL.QueryParser.parseQuery': { 'name': 'Spah.SpahQL.QueryParser.parseQuery', 'type': 'class method', 'path': 'Spah/SpahQL/QueryParser/parseQuery/index.html' },
'Spah.SpahQL.DataHelper.gteSet': { 'name': 'Spah.SpahQL.DataHelper.gteSet', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/gteSet/index.html' },
'new Spah.DOM.Document': { 'name': 'new Spah.DOM.Document', 'type': 'constructor', 'path': 'Spah/DOM/Document/new/index.html' },
'Spah.SpahQL.Callbacks.callbacksForPathInObject': { 'name': 'Spah.SpahQL.Callbacks.callbacksForPathInObject', 'type': 'class method', 'path': 'Spah/SpahQL/Callbacks/callbacksForPathInObject/index.html' },
'Spah.SpahQL.QueryResult#value': { 'name': 'Spah.SpahQL.QueryResult#value', 'type': 'instance property', 'path': 'Spah/SpahQL/QueryResult/prototype/value/index.html' },
'Spah.SpahQL.Token.SelectionQuery#evaluate': { 'name': 'Spah.SpahQL.Token.SelectionQuery#evaluate', 'type': 'instance method', 'path': 'Spah/SpahQL/Token/SelectionQuery/prototype/evaluate/index.html' },
'Spah.SpahQL.QueryResultSet#set': { 'name': 'Spah.SpahQL.QueryResultSet#set', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResultSet/prototype/set/index.html' },
'Spah.SpahQL.DataHelper.mathGt': { 'name': 'Spah.SpahQL.DataHelper.mathGt', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/mathGt/index.html' },
'Spah.State': { 'name': 'Spah.State', 'type': 'class', 'path': 'Spah/State/index.html' },
'Spah.SpahQL.Token.PathComponent': { 'name': 'Spah.SpahQL.Token.PathComponent', 'type': 'class', 'path': 'Spah/SpahQL/Token/PathComponent/index.html' },
'Spah.log': { 'name': 'Spah.log', 'type': 'class method', 'path': 'Spah/log/index.html' },
'Spah.SpahQL.QueryResult#parent': { 'name': 'Spah.SpahQL.QueryResult#parent', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResult/prototype/parent/index.html' },
'Spah.DOM.Modifiers#appendDefaults': { 'name': 'Spah.DOM.Modifiers#appendDefaults', 'type': 'instance method', 'path': 'Spah/DOM/Modifiers/prototype/appendDefaults/index.html' },
'Spah.SpahQL.DataHelper.eqNumberRough': { 'name': 'Spah.SpahQL.DataHelper.eqNumberRough', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/eqNumberRough/index.html' },
'Spah.SpahQL.Token.String': { 'name': 'Spah.SpahQL.Token.String', 'type': 'class', 'path': 'Spah/SpahQL/Token/String/index.html' },
'Spah': { 'name': 'Spah', 'type': 'class', 'path': 'Spah/index.html' },
'Spah.DOM.Blueprint': { 'name': 'Spah.DOM.Blueprint', 'type': 'class', 'path': 'Spah/DOM/Blueprint/index.html' },
'Spah.SpahQL.QueryResult#delete': { 'name': 'Spah.SpahQL.QueryResult#delete', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResult/prototype/delete/index.html' },
'Spah.SpahQL.QueryResult#modified': { 'name': 'Spah.SpahQL.QueryResult#modified', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResult/prototype/modified/index.html' },
'Spah.SpahQL.QueryResultSet#assert': { 'name': 'Spah.SpahQL.QueryResultSet#assert', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResultSet/prototype/assert/index.html' },
'Spah.SpahQL.QueryResultSet#parentPath': { 'name': 'Spah.SpahQL.QueryResultSet#parentPath', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResultSet/prototype/parentPath/index.html' },
'Spah.SpahQL.Token.Set#isRange': { 'name': 'Spah.SpahQL.Token.Set#isRange', 'type': 'instance property', 'path': 'Spah/SpahQL/Token/Set/prototype/isRange/index.html' },
'Spah.SpahQL.QueryResultSet#replace': { 'name': 'Spah.SpahQL.QueryResultSet#replace', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResultSet/prototype/replace/index.html' },
'Spah.isHeadless': { 'name': 'Spah.isHeadless', 'type': 'class method', 'path': 'Spah/isHeadless/index.html' },
'Spah.SpahQL.DataHelper.eqHashRough': { 'name': 'Spah.SpahQL.DataHelper.eqHashRough', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/eqHashRough/index.html' },
'Spah.DOM.Modifiers#remove': { 'name': 'Spah.DOM.Modifiers#remove', 'type': 'instance method', 'path': 'Spah/DOM/Modifiers/prototype/remove/index.html' },
'Spah.SpahQL.Token.ComparisonOperator.parseAt': { 'name': 'Spah.SpahQL.Token.ComparisonOperator.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/ComparisonOperator/parseAt/index.html' },
'Spah.SpahQL.QueryParser.queryCache': { 'name': 'Spah.SpahQL.QueryParser.queryCache', 'type': 'class property', 'path': 'Spah/SpahQL/QueryParser/queryCache/index.html' },
'Spah.State#update': { 'name': 'Spah.State#update', 'type': 'instance method', 'path': 'Spah/State/prototype/update/index.html' },
'Spah.SpahQL.Token.PathComponent.parseAt': { 'name': 'Spah.SpahQL.Token.PathComponent.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/PathComponent/parseAt/index.html' },
'Spah.SpahQL.Token.parseAt': { 'name': 'Spah.SpahQL.Token.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/parseAt/index.html' },
'Spah.SpahQL.QueryRunner.assert': { 'name': 'Spah.SpahQL.QueryRunner.assert', 'type': 'class method', 'path': 'Spah/SpahQL/QueryRunner/assert/index.html' },
'Spah.SpahQL.Token.Boolean.parseAt': { 'name': 'Spah.SpahQL.Token.Boolean.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/Boolean/parseAt/index.html' },
'Spah.SpahQL.DataHelper.eqArray': { 'name': 'Spah.SpahQL.DataHelper.eqArray', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/eqArray/index.html' },
'Spah.SpahQL.DataHelper.eqBooleanRough': { 'name': 'Spah.SpahQL.DataHelper.eqBooleanRough', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/eqBooleanRough/index.html' },
'Spah.SpahQL.DataHelper.modificationSymbol': { 'name': 'Spah.SpahQL.DataHelper.modificationSymbol', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/modificationSymbol/index.html' },
'new Spah.SpahQL.QueryResultSet': { 'name': 'new Spah.SpahQL.QueryResultSet', 'type': 'constructor', 'path': 'Spah/SpahQL/QueryResultSet/new/index.html' },
'Spah.inBrowser': { 'name': 'Spah.inBrowser', 'type': 'class method', 'path': 'Spah/inBrowser/index.html' },
'Spah.SpahQL.Token.Set#tokens': { 'name': 'Spah.SpahQL.Token.Set#tokens', 'type': 'instance property', 'path': 'Spah/SpahQL/Token/Set/prototype/tokens/index.html' },
'Spah.SpahQL.Token.FilterQuery.parseAt': { 'name': 'Spah.SpahQL.Token.FilterQuery.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/FilterQuery/parseAt/index.html' },
'Spah.SpahQL.DataHelper.mathLte': { 'name': 'Spah.SpahQL.DataHelper.mathLte', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/mathLte/index.html' },
'Spah.SpahQL.select': { 'name': 'Spah.SpahQL.select', 'type': 'class method', 'path': 'Spah/SpahQL/select/index.html' },
'Spah.SpahQL.QueryResult#path': { 'name': 'Spah.SpahQL.QueryResult#path', 'type': 'instance property', 'path': 'Spah/SpahQL/QueryResult/prototype/path/index.html' },
'Spah.SpahQL.QueryParser.throwParseErrorAt': { 'name': 'Spah.SpahQL.QueryParser.throwParseErrorAt', 'type': 'class method', 'path': 'Spah/SpahQL/QueryParser/throwParseErrorAt/index.html' },
'Spah.SpahQL.Token.Set#evalStringRange': { 'name': 'Spah.SpahQL.Token.Set#evalStringRange', 'type': 'instance method', 'path': 'Spah/SpahQL/Token/Set/prototype/evalStringRange/index.html' },
'Spah.DOM.Modifiers#reset': { 'name': 'Spah.DOM.Modifiers#reset', 'type': 'instance method', 'path': 'Spah/DOM/Modifiers/prototype/reset/index.html' },
'Spah.SpahQL.Query': { 'name': 'Spah.SpahQL.Query', 'type': 'class', 'path': 'Spah/SpahQL/Query/index.html' },
'Spah.verbose': { 'name': 'Spah.verbose', 'type': 'class property', 'path': 'Spah/verbose/index.html' },
'Spah.SpahQL.QueryResultSet#delete': { 'name': 'Spah.SpahQL.QueryResultSet#delete', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResultSet/prototype/delete/index.html' },
'new Spah.State': { 'name': 'new Spah.State', 'type': 'constructor', 'path': 'Spah/State/new/index.html' },
'new Spah.DOM.Modifiers': { 'name': 'new Spah.DOM.Modifiers', 'type': 'constructor', 'path': 'Spah/DOM/Modifiers/new/index.html' },
'Spah.DOM.Blueprint.compile': { 'name': 'Spah.DOM.Blueprint.compile', 'type': 'class method', 'path': 'Spah/DOM/Blueprint/compile/index.html' },
'Spah.SpahQL': { 'name': 'Spah.SpahQL', 'type': 'class', 'path': 'Spah/SpahQL/index.html' },
'Spah.SpahQL.DataHelper.eqSetStrict': { 'name': 'Spah.SpahQL.DataHelper.eqSetStrict', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/eqSetStrict/index.html' },
'Spah.SpahQL.QueryResultSet': { 'name': 'Spah.SpahQL.QueryResultSet', 'type': 'class', 'path': 'Spah/SpahQL/QueryResultSet/index.html' },
'Spah.SpahQL.Callbacks.callbacks': { 'name': 'Spah.SpahQL.Callbacks.callbacks', 'type': 'class property', 'path': 'Spah/SpahQL/Callbacks/callbacks/index.html' },
'Spah.SpahQL.Token.String.parseAt': { 'name': 'Spah.SpahQL.Token.String.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/String/parseAt/index.html' },
'new Spah.SpahQL.Token.Set': { 'name': 'new Spah.SpahQL.Token.Set', 'type': 'constructor', 'path': 'Spah/SpahQL/Token/Set/new/index.html' },
'Spah.SpahQL.Token.Set.parseAt': { 'name': 'Spah.SpahQL.Token.Set.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/Set/parseAt/index.html' },
'Spah.SpahQL.Token.PathComponent#evaluate': { 'name': 'Spah.SpahQL.Token.PathComponent#evaluate', 'type': 'instance method', 'path': 'Spah/SpahQL/Token/PathComponent/prototype/evaluate/index.html' },
'Spah.DOM.Document#runSync': { 'name': 'Spah.DOM.Document#runSync', 'type': 'instance method', 'path': 'Spah/DOM/Document/prototype/runSync/index.html' },
'Spah.SpahQL.DataHelper.lteSet': { 'name': 'Spah.SpahQL.DataHelper.lteSet', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/lteSet/index.html' },
'Spah.SpahQL.Token.Base.parseAt': { 'name': 'Spah.SpahQL.Token.Base.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/Base/parseAt/index.html' },
'Spah.SpahQL.Callbacks': { 'name': 'Spah.SpahQL.Callbacks', 'type': 'class', 'path': 'Spah/SpahQL/Callbacks/index.html' },
'Spah.SpahQL.DataHelper.gtSet': { 'name': 'Spah.SpahQL.DataHelper.gtSet', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/gtSet/index.html' },
'Spah.SpahQL.Errors.SpahQLRunTimeError': { 'name': 'Spah.SpahQL.Errors.SpahQLRunTimeError', 'type': 'class', 'path': 'Spah/SpahQL/Errors/SpahQLRunTimeError/index.html' },
'Spah.DOM.Errors.InvalidModifierError': { 'name': 'Spah.DOM.Errors.InvalidModifierError', 'type': 'class', 'path': 'Spah/DOM/Errors/InvalidModifierError/index.html' },
'Spah.SpahQL.QueryResultSet#each': { 'name': 'Spah.SpahQL.QueryResultSet#each', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResultSet/prototype/each/index.html' },
'Spah.SpahQL.Token.PathComponent#property': { 'name': 'Spah.SpahQL.Token.PathComponent#property', 'type': 'instance property', 'path': 'Spah/SpahQL/Token/PathComponent/prototype/property/index.html' },
'Spah.SpahQL.QueryRunner': { 'name': 'Spah.SpahQL.QueryRunner', 'type': 'class', 'path': 'Spah/SpahQL/QueryRunner/index.html' },
'Spah.classExtend': { 'name': 'Spah.classExtend', 'type': 'class method', 'path': 'Spah/classExtend/index.html' },
'Spah.SpahQL.Token.Simple#evaluate': { 'name': 'Spah.SpahQL.Token.Simple#evaluate', 'type': 'instance method', 'path': 'Spah/SpahQL/Token/Simple/prototype/evaluate/index.html' },
'Spah.SpahQL.Token.Set': { 'name': 'Spah.SpahQL.Token.Set', 'type': 'class', 'path': 'Spah/SpahQL/Token/Set/index.html' },
'Spah.SpahQL.Token.SelectionQuery.parseAt': { 'name': 'Spah.SpahQL.Token.SelectionQuery.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/SelectionQuery/parseAt/index.html' },
'Spah.SpahQL.Token.Numeric': { 'name': 'Spah.SpahQL.Token.Numeric', 'type': 'class', 'path': 'Spah/SpahQL/Token/Numeric/index.html' },
'Spah.SpahQL.DataHelper.eqRough': { 'name': 'Spah.SpahQL.DataHelper.eqRough', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/eqRough/index.html' },
'Spah.SpahQL.DataHelper.truthySet': { 'name': 'Spah.SpahQL.DataHelper.truthySet', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/truthySet/index.html' },
'Spah.SpahQL.QueryResult#set': { 'name': 'Spah.SpahQL.QueryResult#set', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResult/prototype/set/index.html' },
'Spah.DOM.Modifier': { 'name': 'Spah.DOM.Modifier', 'type': 'class', 'path': 'Spah/DOM/Modifier/index.html' },
'Spah.SpahQL.Token.PathComponent#fetchResultsFromObjectByProperty': { 'name': 'Spah.SpahQL.Token.PathComponent#fetchResultsFromObjectByProperty', 'type': 'instance method', 'path': 'Spah/SpahQL/Token/PathComponent/prototype/fetchResultsFromObjectByProperty/index.html' },
'Spah.SpahQL.DataHelper.eqArrayRough': { 'name': 'Spah.SpahQL.DataHelper.eqArrayRough', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/eqArrayRough/index.html' },
'Spah.SpahQL.QueryResultSet#map': { 'name': 'Spah.SpahQL.QueryResultSet#map', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResultSet/prototype/map/index.html' },
'Spah.SpahQL.assert': { 'name': 'Spah.SpahQL.assert', 'type': 'class method', 'path': 'Spah/SpahQL/assert/index.html' },
'Spah.SpahQL.Token.SelectionQuery#useRoot': { 'name': 'Spah.SpahQL.Token.SelectionQuery#useRoot', 'type': 'instance property', 'path': 'Spah/SpahQL/Token/SelectionQuery/prototype/useRoot/index.html' },
'Spah.SpahQL.Token.SelectionQuery#pathComponents': { 'name': 'Spah.SpahQL.Token.SelectionQuery#pathComponents', 'type': 'instance property', 'path': 'Spah/SpahQL/Token/SelectionQuery/prototype/pathComponents/index.html' },
'Spah.SpahQL.QueryResultSet#length': { 'name': 'Spah.SpahQL.QueryResultSet#length', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResultSet/prototype/length/index.html' },
'Spah.DOM': { 'name': 'Spah.DOM', 'type': 'class', 'path': 'Spah/DOM/index.html' },
'Spah.DOM.Errors': { 'name': 'Spah.DOM.Errors', 'type': 'class', 'path': 'Spah/DOM/Errors/index.html' },
'Spah.SpahQL.DataHelper.eqSetRough': { 'name': 'Spah.SpahQL.DataHelper.eqSetRough', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/eqSetRough/index.html' },
'Spah.SpahQL.QueryResult#replace': { 'name': 'Spah.SpahQL.QueryResult#replace', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResult/prototype/replace/index.html' },
'Spah.SpahQL.Errors.SpahQLError': { 'name': 'Spah.SpahQL.Errors.SpahQLError', 'type': 'class', 'path': 'Spah/SpahQL/Errors/SpahQLError/index.html' },
'Spah.SpahQL.Token.Set#evaluate': { 'name': 'Spah.SpahQL.Token.Set#evaluate', 'type': 'instance method', 'path': 'Spah/SpahQL/Token/Set/prototype/evaluate/index.html' },
'Spah.SpahQL.Token.PathComponent#filterQueries': { 'name': 'Spah.SpahQL.Token.PathComponent#filterQueries', 'type': 'instance property', 'path': 'Spah/SpahQL/Token/PathComponent/prototype/filterQueries/index.html' },
'Spah.DOM.Document#runElementSync': { 'name': 'Spah.DOM.Document#runElementSync', 'type': 'instance method', 'path': 'Spah/DOM/Document/prototype/runElementSync/index.html' },
'Spah.SpahQL.DataHelper.mathGte': { 'name': 'Spah.SpahQL.DataHelper.mathGte', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/mathGte/index.html' },
'Spah.SpahQL.QueryResult#select': { 'name': 'Spah.SpahQL.QueryResult#select', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResult/prototype/select/index.html' },
'Spah.SpahQL.Token.Base': { 'name': 'Spah.SpahQL.Token.Base', 'type': 'class', 'path': 'Spah/SpahQL/Token/Base/index.html' },
'Spah.SpahQL.QueryResult#sourceData': { 'name': 'Spah.SpahQL.QueryResult#sourceData', 'type': 'instance property', 'path': 'Spah/SpahQL/QueryResult/prototype/sourceData/index.html' },
'Spah.DOM.Modifiers#modules': { 'name': 'Spah.DOM.Modifiers#modules', 'type': 'instance property', 'path': 'Spah/DOM/Modifiers/prototype/modules/index.html' },
'Spah.SpahQL.DataHelper.eqHash': { 'name': 'Spah.SpahQL.DataHelper.eqHash', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/eqHash/index.html' },
'Spah.SpahQL.Token#toSet': { 'name': 'Spah.SpahQL.Token#toSet', 'type': 'instance method', 'path': 'Spah/SpahQL/Token/prototype/toSet/index.html' },
'Spah.SpahQL.DataHelper.hashKeys': { 'name': 'Spah.SpahQL.DataHelper.hashKeys', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/hashKeys/index.html' },
'new Spah.SpahQL.QueryResult': { 'name': 'new Spah.SpahQL.QueryResult', 'type': 'constructor', 'path': 'Spah/SpahQL/QueryResult/new/index.html' },
'Spah.SpahQL.QueryResult': { 'name': 'Spah.SpahQL.QueryResult', 'type': 'class', 'path': 'Spah/SpahQL/QueryResult/index.html' },
'Spah.SpahQL.QueryResult#type': { 'name': 'Spah.SpahQL.QueryResult#type', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResult/prototype/type/index.html' },
'Spah.SpahQL.DataHelper.compare': { 'name': 'Spah.SpahQL.DataHelper.compare', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/compare/index.html' },
'Spah.SpahQL.Token.SelectionQuery': { 'name': 'Spah.SpahQL.Token.SelectionQuery', 'type': 'class', 'path': 'Spah/SpahQL/Token/SelectionQuery/index.html' },
'Spah.SpahQL.DataHelper.eqStringRough': { 'name': 'Spah.SpahQL.DataHelper.eqStringRough', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/eqStringRough/index.html' },
'Spah.SpahQL.DataHelper.coerceKeyForObject': { 'name': 'Spah.SpahQL.DataHelper.coerceKeyForObject', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/coerceKeyForObject/index.html' },
'Spah.SpahQL.QueryResult#parentPath': { 'name': 'Spah.SpahQL.QueryResult#parentPath', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResult/prototype/parentPath/index.html' },
'Spah.SpahQL.DataHelper.eq': { 'name': 'Spah.SpahQL.DataHelper.eq', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/eq/index.html' },
'Spah.SpahQL.Token.PathComponent#fetchResultsFromObjectByKey': { 'name': 'Spah.SpahQL.Token.PathComponent#fetchResultsFromObjectByKey', 'type': 'instance method', 'path': 'Spah/SpahQL/Token/PathComponent/prototype/fetchResultsFromObjectByKey/index.html' },
'Spah.SpahQL.Token.Boolean': { 'name': 'Spah.SpahQL.Token.Boolean', 'type': 'class', 'path': 'Spah/SpahQL/Token/Boolean/index.html' },
'Spah.SpahQL.QueryResult#keyName': { 'name': 'Spah.SpahQL.QueryResult#keyName', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResult/prototype/keyName/index.html' },
'Spah.SpahQL.QueryResultSet.deleteAll': { 'name': 'Spah.SpahQL.QueryResultSet.deleteAll', 'type': 'class method', 'path': 'Spah/SpahQL/QueryResultSet/deleteAll/index.html' },
'Spah.SpahQL.Token.PathComponent#recursive': { 'name': 'Spah.SpahQL.Token.PathComponent#recursive', 'type': 'instance property', 'path': 'Spah/SpahQL/Token/PathComponent/prototype/recursive/index.html' },
'Spah.SpahQL.Token.throwParseErrorAt': { 'name': 'Spah.SpahQL.Token.throwParseErrorAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/throwParseErrorAt/index.html' },
'Spah.SpahQL.DataHelper.jointSet': { 'name': 'Spah.SpahQL.DataHelper.jointSet', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/jointSet/index.html' },
'Spah.SpahQL.QueryResultSet#item': { 'name': 'Spah.SpahQL.QueryResultSet#item', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResultSet/prototype/item/index.html' },
'Spah.DOM.Modifiers#add': { 'name': 'Spah.DOM.Modifiers#add', 'type': 'instance method', 'path': 'Spah/DOM/Modifiers/prototype/add/index.html' },
'Spah.SpahQL.Token': { 'name': 'Spah.SpahQL.Token', 'type': 'class', 'path': 'Spah/SpahQL/Token/index.html' },
'Spah.SpahQL.QueryResultSet#select': { 'name': 'Spah.SpahQL.QueryResultSet#select', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResultSet/prototype/select/index.html' },
'Spah.SpahQL.DataHelper.objectType': { 'name': 'Spah.SpahQL.DataHelper.objectType', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/objectType/index.html' },
'Spah.SpahQL.Token.PathComponent#key': { 'name': 'Spah.SpahQL.Token.PathComponent#key', 'type': 'instance property', 'path': 'Spah/SpahQL/Token/PathComponent/prototype/key/index.html' },
'Spah.SpahQL.Token.KeyName.parseAt': { 'name': 'Spah.SpahQL.Token.KeyName.parseAt', 'type': 'class method', 'path': 'Spah/SpahQL/Token/KeyName/parseAt/index.html' },
'Spah.SpahQL.Token.FilterQuery#evaluate': { 'name': 'Spah.SpahQL.Token.FilterQuery#evaluate', 'type': 'instance method', 'path': 'Spah/SpahQL/Token/FilterQuery/prototype/evaluate/index.html' },
'Spah.SpahQL.Token.FilterQuery': { 'name': 'Spah.SpahQL.Token.FilterQuery', 'type': 'class', 'path': 'Spah/SpahQL/Token/FilterQuery/index.html' },
'Spah.DOM.Blueprint#render': { 'name': 'Spah.DOM.Blueprint#render', 'type': 'instance method', 'path': 'Spah/DOM/Blueprint/prototype/render/index.html' },
'Spah.SpahQL.Query#rawString': { 'name': 'Spah.SpahQL.Query#rawString', 'type': 'instance property', 'path': 'Spah/SpahQL/Query/prototype/rawString/index.html' },
'Spah.SpahQL.Query#primaryToken': { 'name': 'Spah.SpahQL.Query#primaryToken', 'type': 'instance property', 'path': 'Spah/SpahQL/Query/prototype/primaryToken/index.html' },
'Spah.DOM.Document': { 'name': 'Spah.DOM.Document', 'type': 'class', 'path': 'Spah/DOM/Document/index.html' },
'Spah.logMessages': { 'name': 'Spah.logMessages', 'type': 'class property', 'path': 'Spah/logMessages/index.html' },
'Spah.SpahQL.Query#assertion': { 'name': 'Spah.SpahQL.Query#assertion', 'type': 'instance property', 'path': 'Spah/SpahQL/Query/prototype/assertion/index.html' },
'Spah.init': { 'name': 'Spah.init', 'type': 'class method', 'path': 'Spah/init/index.html' },
'Spah.SpahQL.Token.KeyName': { 'name': 'Spah.SpahQL.Token.KeyName', 'type': 'class', 'path': 'Spah/SpahQL/Token/KeyName/index.html' },
'Spah.SpahQL.Callbacks.pathModifiedOnObject': { 'name': 'Spah.SpahQL.Callbacks.pathModifiedOnObject', 'type': 'class method', 'path': 'Spah/SpahQL/Callbacks/pathModifiedOnObject/index.html' },
'Spah.DOM.Modifiers#indexOf': { 'name': 'Spah.DOM.Modifiers#indexOf', 'type': 'instance method', 'path': 'Spah/DOM/Modifiers/prototype/indexOf/index.html' },
'Spah.SpahQL.QueryResult#triggerModificationCallbacks': { 'name': 'Spah.SpahQL.QueryResult#triggerModificationCallbacks', 'type': 'instance method', 'path': 'Spah/SpahQL/QueryResult/prototype/triggerModificationCallbacks/index.html' },
'Spah.SpahQL.DataHelper.mathLt': { 'name': 'Spah.SpahQL.DataHelper.mathLt', 'type': 'class method', 'path': 'Spah/SpahQL/DataHelper/mathLt/index.html' },
'Spah.SpahQL.QueryParser': { 'name': 'Spah.SpahQL.QueryParser', 'type': 'class', 'path': 'Spah/SpahQL/QueryParser/index.html' }
};